### ISSUE TITLE
Compatibility with Lua 5.3.2

### ISSUE THREAD

**Issue by NSP-0123456** [zetamatta/nyagos#102]
I updated lua53.dll to 5.3.2 and i get error with nyagos. 
How to upgrade lua interface to 5.3.2 or is it possible to be compatible from 5.3.0 up to 5.3.xxx

**Comment by zetamatta** [comment]
Is Your lua53.dll for 32bit or 64bit ? If it differs from NYAGOS's bit-size, they will not run.

The last version NYAGOS.exe (5.1.1_0) are based on lua53.dll in Lua Binaries 5.3.2.

- `nyagos-4.1.1_0-386.zip` includes lua53.dll in`lua-5.3.2_Win32_dllw4_lib.zip`.
- `nyagos-4.1.1_0-amd64.zip` includes lua53.dll in`lua-5.3.2_Win64_dllw4_lib.zip`

Would you test them ?

**Comment by NSP-0123456** [comment]
Great !
All is working.
I did tests with file in "release"  and from my compiled version of lua53.dll  (TDM-gcc64) and from git pull of nyagos.
Thanks !
