### ISSUE TITLE
On `conEmu`, built-in `echo` freezes

### ISSUE THREAD

**Issue by zetamatta** [zetamatta/nyagos#105]
- OK
    - Command Prompt
    - console2
    - ckw-mod unicoded
- NG
    - conEmu

- https://twitter.com/Masahito/status/689294522224738304
- https://twitter.com/Masahito/status/689452814125268993

**Comment by zetamatta** [comment]
NYAGOS works with no problems but 🍣

![conemuxnyagos](https://cloud.githubusercontent.com/assets/3752189/12534916/9c40656c-c2b1-11e5-9249-704ed2022f65.png)

**Comment by Maximus5** [comment]
Did you mean "the symbol is cropped"?

**Comment by zetamatta** [comment]
I do not consider it the problem to solve **in this issue**.
The report I heard is that nyagos freezes when it runs on ConEmu and does `echo` something.

I found some symbol are cropped. It is caused because the width of font differs from one defined by unicode-rule. So, I consider it is not bug both for NYAGOS and ConEmu.

( But, NYAGOS counts the width of character by how many width cursor moves when it is printed. )

**Comment by zetamatta** [comment]
If you want NYAGOS to fix something, create another issue, please.
