### ISSUE TITLE
Small modification for make install

### ISSUE THREAD

**Issue by NSP-0123456** [zetamatta/nyagos#107]
When launching robocopy from make.cmd the shell windows stay opened if you change start by call (line 64) solve the issue. Another way, is to remove completely the start itself with install. and the goto end as the next section is the one  called.

**Comment by zetamatta** [comment]
I want to leave the window open to confirm whether copying nyagos.exe is success or not.
Sometimes it fails.

**Comment by NSP-0123456** [comment]
What you want, you can add pause after the robocopy command my concern is more to not have any new window started rather having it waiting....

**Comment by zetamatta** [comment]
`pause` does not work as I expect. `taskkill.exe` closes the window nyagos.exe runs.

```
$ git diff
diff --git a/make.cmd b/make.cmd
index 3c3f037..84f1920 100644
--- a/make.cmd
+++ b/make.cmd
@@ -61,16 +61,19 @@ goto build
             echo Please %0.cmd install EXIST\PATH\TO\BIN,  once
             goto end
         )
-        start %~0 install.
-        goto end
+rem        start %~0 install.
+rem        goto end

 :install.
         robocopy nyagos.d "%INSTALLDIR%\nyagos.d" /E
+        pause
         taskkill /F /im nyagos.exe
+        pause
         copy nyagos.exe "%INSTALLDIR%\."
         copy nyagos.lua "%INSTALLDIR%\."
         copy nyole.dll "%INSTALLDIR%\."
         if not exist "%INSTALLDIR%\lua53.dll" copy lua53.dll "%INSTALLDIR%\."
+        pause
         goto end
```

`pause` after `taskkill` was not called on my environment.

If make.cmd is called on cmd.exe, there are no problems. But, I calles make.cmd on nyagos.exe.

**Comment by zetamatta** [comment]
On cbf8b4520427eb0bb5c0c432e60996496bb29187 , `make install` does not make new console when executable whose directory is desitination is not busy.

**Comment by NSP-0123456** [comment]
Thanks a lot ! (All is working fine from cmd/cmder....)
