### ISSUE TITLE
nyagos built-in echoでの改行付与がLF

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#124]
nyagos on ConEmuで作業していて、以下となりました。

```
$ which echo
echo: built-in command

echo abc >> README.md(CRLF)
gvim README.md &
> 123^M
> abc
> [ff=unix]
```

この動作(LFで改行)は意図的でしょうか?

そうである場合、なにかチューニング方法はありますでしょうか。

Windows上でのgitもこなれてきていて、CRLFでチェックアウト、チェックインでLF変換でもトラブルはないことが多いため、Windows上ツールとしてはCRLFでの改行がなされる(設定できる)と助かるのですが。

**Comment by zetamatta** [comment]
お世話になっております。

LF出力は特に意図したものではなく、Go言語での出力の仕方がそのまま出てしまっているのかと思います。
「文字コードが UTF8 なので、改行も LF なのもいいか…」などと考えていたのですが、CRLF にするよう改めたいと思います。

もしお急ぎでしたら：

```
nyagos.alias.echo = function(args) nyagos.write(table.concat(args,' ').."\r\n") end
```

という一文を  `~\.nyagos` に書いていただいて、echo そのものを差し替えていただくという手もあります。

以上、よろしくお願いいたします。

**Comment by zetamatta** [comment]
ソース上は対応済ですが、バイナリファイルへの反映は、仕掛中の別件もありますので、もう少々お待ちください。（よろしければ、上記の `~/.nyagos` の暫定処置でごまかしておいていただけますでしょうか）

以上、よろしくお願いいたします。

**Comment by tsuyoshicho** [comment]
了解です。自分はnyagosをchocolateyからインストールする人なので、反映が遅くなってしまうでしょうし、上記設定を入れることとします。

ありがとうございました。

**Comment by zetamatta** [comment]
修正 bb8bd3950619342211491ef62fbc23d1446333c6 を取り込んだバイナリバージョン [4.1.3_0](https://github.com/zetamatta/nyagos/releases/tag/4.1.3_0) をリリースしたため、 本issue はクローズさせていただきます。
