### ISSUE TITLE
ヒストリがファイルに保存されない

### ISSUE THREAD

**Issue by 3bch** [zetamatta/nyagos#138]
メモリ上にあるうちはヒストリが使えてますが、ファイルに保存されておらず、一回 exit すると消えてしまいます。
`~/AppData/Roaming/NYAOS_ORG/nyagos.history` も確認してみるとファイルができてますが、0バイトのままとなってました。

確認した nyagos のバージョンは 4.1.3_0 です。
発生した現象としては #39 と同じです。

ちょっとソースも覗いてみましたが、左右で同じ関数の結果を比較しており、以下の条件が怪しい気がします。
https://github.com/zetamatta/nyagos/blob/4.1.3_0/main/nyagos.go#L211

**Comment by zetamatta** [comment]
ありがとうございます。ソースのご指摘はドンピシャです。

あそこは元々「ヒストリが増えた時だけ、ファイルに保存する」という意味のコードが入っていたんですが、標準入力からのコマンド入力を Ok にする修正（8c7b0625）の際、その意味を忘れたまま機械的に書き換えてしまってミスってしまったようです。

ソースは先ほど修正（65fdec8）しましたが、バイナリ版にもできるだけ早く反映します。

**Comment by zetamatta** [comment]
当問題に対する修正（ 65fdec8 ）を含んだ [4.1.3_1](https://github.com/zetamatta/nyagos/releases/tag/4.1.3_1) を公開しました。

**Comment by 3bch** [comment]
4.1.3_1 で直っていることを確認できました。
修正ありがとうございます。
