### ISSUE TITLE
nyagos.lines で改行コードが残っている

### ISSUE THREAD

**Issue by hami-jp** [zetamatta/nyagos#144]
```lua
for line in nyagos.lines(path) do
  nyagos.write(line) -- line の行末に改行コードが残ってる
end
```

Lua拡張の `nyagos.lines(path)` で行読み込みを行なうと、行末の改行コードが残ってます。
`io.lines(path)` は改行コードを削除する仕様みたいなので一応報告しておきます。

**Comment by zetamatta** [comment]
ありがとうございます。`nyagos.lines(path)` については修正しました。
が、あわせて、別件の不具合（ #146 , #147）を見つけてしまいました。
各々、個別に対応してゆきたいと思います。

**Comment by zetamatta** [comment]
4.1.4_0 にて、バイナリにも反映しました。
