### ISSUE TITLE
"?:-1: attempt to call a table value (upvalue '?')"とは何を意味していますか？

### ISSUE THREAD

**Issue by gracix** [zetamatta/nyagos#155]
Nyagos起動と同時に "?:-1: attempt to call a table value (upvalue '?')" という表示が出てきます。
また、コマンド起動ごとに同じメッセージが表示されています。

Nyagos 4.1.0_0 ～ Nyagos 4.1.4_1 まで確認しました。
すべてWindows (Win7 64bit) / Nyagos amd64です。

このメッセージが出なくするにはどこを調べればよいでしょうか？
アドバイスいただけると助かります。

**Comment by zetamatta** [comment]
＞また、コマンド起動ごとに同じメッセージが表示されています。

どうも、Lua の何らかのフック変数に呼び出せないもの（この場合テーブル）などが
入っているように見受けられます。

フックとしては**プロンプト表示**(nyagos.prompt=)、**逆クォート変換のためのフィルター**
(nyagos.filter=)、**拡張子への関連付け**(nyagos.argsfilter=)などがあります。
これらを変更するスクリプトが古いファイルのままになっているのかもしれません。

4.0 → 4.1 でnyagos の内蔵 Lua の仕様がかわり、グローバル変数が大幅に制限されたので、
それが影響している可能性もあります。
割合は少ないですが for ~ in nyagos.**** do～end などでも発生することがあります（その場合、
本体側の不具合が多い）。

発生率からすると、経験的に、プロンプト関係の設定(nyagos.prompt=)が一番ありえると思います。

可能であれば、~/.nyagos と nyagos.lua 、nyagos.d 以下のファイルを一度バックアップをとって、
プログラム標準で添付されているものだけを展開してみていただけますでしょうか？
それで問題は再発するでしょうか？
（特に nyagos.d 以下は、過去の古いファイルが残って問題源になりやすくなっています）

もし、場所の特定が必要であれば、銃弾爆撃的な消去法ですが、
下記のような方法があります。

1.   ~/.nyagos だけを別の適当なディレクトリへ移動して、nyagos を起動してみる
  - エラーが消えたら .nyagos 内に原因がある
2.  nyagos.d/*.lua の半分のファイルを、別の適当なディレクトリへ移動して nyagos を起動してみる
   - エラーが消えたら、移動させた側のファイルに
   - エラーが消えなかったら、移動させなかった側のファイルに原因がある
   - 変化があったら、エラー源があった方のファイル群全体を二つに分けて、同じことを繰り返してみる
3. nyagos.lua を別のディレクトリへ移動させてみる
   - それでもエラーが残っていたら、EXEファイル本体側に原因がある（不具合）

おそれいりますが、このあたりご確認いただけますでしょうか

**Comment by gracix** [comment]
大変丁寧な返信ありがとうございました！

~/.nyagos がありましたのでそれを消してみたところ、上記メッセージは出なくなり、解決いたしました。

問題の設定ファイルは以下のような状態でした。

`
-- This is a sample .nyagos written with Lua.
-- Edit and put it on %USERPROFILE% or %HOME%

-- Simple Prompt for CMD.EXE
set{
    PROMPT='$L'.. nyagos.getenv('COMPUTERNAME') .. ':$P$G$_$$$s'
}

-- Coloring Prompt for NYAGOS.exe
local prompter=nyagos.prompt
nyagos.prompt = function(this)
    return prompter('$e[36;40;1m'..this..'$e[37;1m')
end

-- vim:set ft=lua: --

`

**Comment by zetamatta** [comment]
ご連絡ありがとうございます。こちらでも思い当るところを検証していたところでした。問題箇所は

```
local prompter=nyagos.prompt
nyagos.prompt = function(this)
return prompter('$e[36;40;1m'..this..'$e[37;1m')
end
```

でした。これは 4.0.* で提供していたデフォルトの .nyagos に由来する箇所かと思われますが、4.1.* ではグローバル変数の変更がメイン以外のスレッド（プロンプト表示含む）に反映されなくなったり、フックにクロージャーが使えなくなったため、書き換えが必要になっていました（他のスレッドで参照できると、タイミングによっては Lua の方がクラッシュしてしまうという問題がありまして…）

今回の場合、local変数prompter が、実際のプロンプト表示のスレッドでは nil に見えてしまっていました（nyagos.prompt がクロージャではなく、シンプル関数と見なされるようになったため）

お手数ですが、実行ファイルを 4.1.4_1 に更新していただいた上で、上記の引用部分を該当部分を下記のように改めてみていただけないでしょうか？（nyagos.default_prompt は 4.1.4 以降のみのため）

```
nyagos.prompt = function(this)
    return nyagos.default_prompt('$e[36;40;1m'..this..'$e[37;1m')
end
```

なお、本件は @gracix さん以外の環境でもかなりの率で起こり得る問題かと思いますので、別途、なんらかの対策を打ちたいと考えております。
（文書レベルの注意書きか、あるいは Warning 出力か、仕組み的な対策か、どうするかは検討中ですが）

今回のご報告で、重要な問題があきらかになりました。たすかります。

以上、よろしくお願いいたします。

**Comment by gracix** [comment]
確認ありがとうございます。

4.1.4_1に更新し、ご指定のコードを ~/.nyagos に設定したところ、表示も今までどおりになり、エラーもなくなりました。

ありがとうございました！
