### ISSUE TITLE
%u+0000% causes a panic

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#156]
```batch
$ echo %u+0000%
```
```log
************ Panic Occured. ***********
invalid argument
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        C:/Tools/go32/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        C:/Tools/go32/src/runtime/debug/stack.go:16 +0x1a
main.when_panic()
        I:/Freespace/go/nyagos/nyagos/main/nyagos.go:91 +0x19b
panic(0x56c260, 0x128a07a8)
        C:/Tools/go32/src/runtime/panic.go:426 +0x3fd
_/I_/Freespace/go/nyagos/nyagos/lua.Lua.PushString(0x3258490c, 0x128cef61, 0x1)
        I:/Freespace/go/nyagos/nyagos/lua/push.go:51 +0x90
main.newArgHook(0x128a4000, 0x128cef70, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        I:/Freespace/go/nyagos/nyagos/main/lua.go:56 +0x228
_/I_/Freespace/go/nyagos/nyagos/interpreter.(*Interpreter).Interpret(0x128a4000, 0x128cee90, 0xd, 0x0, 0x0, 0x0)
        I:/Freespace/go/nyagos/nyagos/interpreter/interpreter.go:237 +0x3f9
main.main()
        I:/Freespace/go/nyagos/nyagos/main/nyagos.go:256 +0x12a6
*** Please copy these error message ***
*** And hit ENTER key to quit.      ***
```

It seems that NULL character is passed to `syscall.BytePtrFromString(string)`

**Comment by zetamatta** [comment]
`syscall.BytePtrFromString(string)` returns error when string contains NUL.

In this case, the `string` is for lua53.dll and lua53.dll can accept strings contains NUL.
So, stoped to use `syscall.BytePtrFromString(string)` and wrote codes to copy string to byte-array.

Now, `echo X%U0000%Y > t` works as we excepted.

Thank you.

----
‘syscall.BytePtrFromString(string)‘ は NUL を含む文字列の場合、エラーを返すようになっていました。
今回の場合では、この `string` は lua53.dll 向けで、lua53.dll は NUL を含む文字列を受け入れます。
そのため、‘syscall.BytePtrFromString(string)‘ を使うのをやめ、string から byte配列へコピーするコードを書きました。

結果、`echo X%U+0000%Y > t` が期待どおり動くようになっています。

ありがとうございました。

**Comment by nocd5** [comment]
Thanks for your speedy response. I made sure the issue fixed at 21fe7e6.
