### ISSUE TITLE
ウインドウサイズ変更直後の横スクロールで表示が崩れる

### ISSUE THREAD

**Issue by rururutan** [zetamatta/nyagos#157]
**バージョン**
Nyagos 4.1.4_1で確認

**現象**
コンソールのウインドウサイズを変更した直後に長いコマンドラインを入力させ、横スクロールさせると画面の整合性がとれずおかしくなります。

特にサイズを縮めると画像の様に画面が崩れます。スクロール開始する'9'を打った時の画像。

![nyagos_scroll_bug](https://cloud.githubusercontent.com/assets/638143/17083398/c001befc-51da-11e6-8409-c58c136b6bfb.gif)

cmd単体だとプロパティ ウインドウ->ウインドウのサイズ->幅を変更する事で。
conemu系ならウインドウの幅を変えることで再現します。

**Comment by zetamatta** [comment]
ご指摘ありがとうございます。

ウインドウサイズの変更イベントを拾って、サイズの変更を直ちに反映するよう修正してみました。入力途中の一行入力はいったんその場で改行して、新しい行の幅に合わせて再表示するようにしています。

ソース上は、外部に追い出した一文字入力クラスを更新したので、`go get github.com/zetamatta/go-getch` を再実行する必要があります。バイナリへの反映もそのうち行う予定です。

以上、とりいそぎ

**Comment by zetamatta** [comment]
変更を反映したバイナリ [4.1.5_0](https://github.com/zetamatta/nyagos/releases/tag/4.1.5_0) を公開しました。

**Comment by rururutan** [comment]
![nyagos](https://cloud.githubusercontent.com/assets/638143/17274188/5162af26-570f-11e6-86a8-1d720897eff6.gif)
更新ありがとうございます。試してみましたがまだ駄目な様です。
再現動画を添付します。

**Comment by zetamatta** [comment]
わざわざの動画採取、ご報告ありがとうございます。

既に入力したテキストが画面幅を超過した状態での、端末サイズ変更は試していたのですが、
何も入力していない状態からの、端末サイズ変更は未試験でした。
対応のケース漏れだったようです。

ご提示の動作を確認しましたので、再度修正いたしますので、少々お待ちいただけますでしょうか

**Comment by zetamatta** [comment]
すみません。こちらを試してみていただけますでしょうか
[nyagos-20160731-386-tmp.zip](https://github.com/zetamatta/nyagos/files/392271/nyagos-20160731-386-tmp.zip)

**Comment by rururutan** [comment]
素早い対応有難うございます。不具合は直っていることを確認しました。

1つだけ気になったので確認させてください。
サイズを変更することによりプロンプトが何度も改行?されるのは仕様でしょうか?

![nyagos_resize](https://cloud.githubusercontent.com/assets/638143/17275469/4b5ab5a8-5744-11e6-99c2-03ae9a8bffe6.gif)

conemuなのは動作が分かりやすい為。
問題ないようでしたら本件クローズしてください。

**Comment by zetamatta** [comment]
はい。それは今のところ仕様です。

画面サイズを変えることにより、カーソル位置を見失う恐れがあるため、とりあえず、改行させてからプロンプトを再表示させて、カーソル位置をリセットさせています。

コンソールのAPIを駆使すれば、そんなことをする必要は全くないんですが、妙に設計でカーソル移動量とかにこだわったりしてしまったせいもありまして…いずれ改善したいと思います。
