### ISSUE TITLE
Autocorrection

### ISSUE THREAD

**Issue by malys** [zetamatta/nyagos#166]
Hi,
Is it possible to integrate something like 
[The Fuck](https://github.com/nvbn/thefuck) in nyagos?

Do you plan it?

Thanks,

**Comment by zetamatta** [comment]
I suppose Lua may make it possible. The code to repeat the previous command is below

```
   lua_e "nyagos.exec( nyagos.gethistory( nyagos.gethistory()-2 ))"
```

So, if there is the code to correct the string of previous commandline, it will be possible.
If the pull request is given, I will merge it in `nyagos.d/catalog/` . But, I will not make them by myself.

**Comment by malys** [comment]
Thanks you for your advice. I will try to implement it in LUA. If I succeed, I would send you a pull request.
Bye
