### ISSUE TITLE
ConEmu + nyagos でリモートログイン時の日本語入力ができない

### ISSUE THREAD

**Issue by terepanda** [zetamatta/nyagos#175]
こんにちは。
Windows 10 で ConEmu(161206 64bit) から nyagos(4.1.7_0-amd64) を使用させていただいております。
Git for Windows をインストールして SSH を使えるようにした上でリモートマシンにログインした後、日本語入力をすると、変換を確定するタイミングで文字が消えてしまいます。
![nyagos](https://cloud.githubusercontent.com/assets/1763675/21585167/5a6c71c4-d0fe-11e6-9aa6-f74b89736ec7.gif)

ConEmu の設定の問題なのかもしれませんが、ローカルマシンでの日本語入力は問題なくできており、SSH でリモートマシンにログインした時だけ日本語入力ができません。また、日本語入力ができる PuTTY(putty-0.67-jp20160306) を ConEmu から使用した場合は問題ありませんでした。もし、nyagos の設定等で解決できそうであれば教えていただけますか？
よろしくお願いします。

**Comment by terepanda** [comment]
すみません。nyagos 単体でリモートログインした場合は問題なく日本語入力ができました。ConEmu からnyagos を使った時だけの問題だったようです。失礼しました。

**Comment by zetamatta** [comment]
ご連絡ありがとうございます。ssh でリモートログインしているという場合ということは、シェルはログイン先のもの（bash？）が動いているので、NYAGOS が介在している箇所はなく（NYAGOSはこの間ずっとプロセス終了を待っています）、基本的に ターミナル（ConEmu）側の問題かと思います。

また、何かありましたら、ご相談ください

**Comment by terepanda** [comment]
ご返信ありがとうございます。NYAGOS は関係なかったんですね。申し訳ありませんでした。:cold_sweat:
原因としては、ConEmu 上で ssh を実行する時に、コードページが 932 ではなく 65001 になっていると、ログイン先で日本語が使えなくなるようでした。普段は chcp 65001 で使用しているのですが、ssh に alias を設定して chcp 932 に変更してから実行するようにしました。NYAGOS が柔軟にエイリアスを設定できるので助かりました。:smile:

**Comment by zetamatta** [comment]
なるほど、ssh でログインした先が UTF8 で標準出力・エラー出力を返してくるから、ANSI のコードページを変えなければいけなかった…というわけですね。

NYAGOS 実行中、 NYAGOS が内部で出力している文字列は UTF8→UTF16→Unicode-API で Unicode として出せますが、外部コマンドについては UTF8 → ANSI-API で現在のコードページの文字コードとして解釈されますので、確かに UTF8 が CP932(ShiftJIS)と解釈されてしまい、文字化けが発生する可能性が高いです。

直接関係なかったとしても事例としては参考になりますので、こちらにご報告いただくのは全くもって問題ありません（もともと閑古鳥が鳴いておりますので）

今後ともよろしくお願いいたします。
