### ISSUE TITLE
%HOME%\.nyagos is not loaded

### ISSUE THREAD

**Issue by tyochiai** [zetamatta/nyagos#178]
After commit d356e46, %HOME%/.nyagos is not loaded.

Maybe User.HomeDir is always %USERPROFILE%, regardless of setting %HOME%.
So you should change the spec to use only %USERPROFILE%, or revert it.

OS: Windows 10 Pro
go version: 1.7.5 windows/amd64

**Comment by tyochiai** [comment]
bad timing... ><
It is already resolve at 44d0a50.

**Comment by zetamatta** [comment]
m(_ _)m

It may be bad change to stop read %HOME%...

**Comment by zetamatta** [comment]
I forgot the influence by the change. Thanks to make issue.
