### ISSUE TITLE
Enhancement: completion subcommand level 2

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#205]
現在梱包されているsubcomplete.luaでは1段階のコマンドの補完ができますが、これを2段階かつユーザー定義可能にするのはどうでしょうか?

試案を作りましたので、pull-reqします

**Comment by zetamatta** [comment]
ありがとうございます。
元々つけている補完拡張はそれほど練られたものでもないので、改善案があれば基本 Welcome です。
マージさせていただきました。
