### ISSUE TITLE
.nyagos でのバッチ実行時に "main/lua_cmd.go: cmdExec: not found interpreter object" と表示される

### ISSUE THREAD

**Issue by Matsuyanagi** [zetamatta/nyagos#214]
nyagos 4.1.9.2-amd64, -386
Windows10, Windows7
ConEmu 160710

nyagos 4.1.7 から nyagos 4.1.9.2 に更新したところ、
.nyagos 内で VisualStudio の環境変数設定バッチを実行したときに "main/lua_cmd.go: cmdExec: not found interpreter object"
のメッセージが出るようになりました。

.nyagos
```
nyagos.exec{ "source","C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" }
```

メッセージは出るものの、環境変数自体は設定されています。
nyagos 4.1.7 , 4.1.6 の時には表示されません。
どのバージョンから変化したのかはわかりません。
再現はするでしょうか

**Comment by zetamatta** [comment]
ご報告ありがとうございます。

4.1.9_2 , および、最新ソースでも再現しました。直接の実害はないと思いますが、ここで出るということは他の不具合を引き起こす可能性があるので、できるだけ早く対応したいと思います。
4.1.9_3 を出しますので、少々お待ちいただけますでしょうか。

以上、よろしくお願いいたします。

**Comment by zetamatta** [comment]
問題点を修正した 4.1.9_3 を公開しました。こちらにて修正されているか、ご確認いただけますでしょうか

https://github.com/zetamatta/nyagos/releases/tag/4.1.9_3

**Comment by Matsuyanagi** [comment]
4.1.9_3 amd64, 386 の両方でメッセージが表示されなくなっていることを確認しました。
対応ありがとうございました。

**Comment by zetamatta** [comment]
ご確認ありがとうございます。
