### ISSUE TITLE
dir | find "<DIR>"

### ISSUE THREAD

**Issue by zkangaroo** [zetamatta/nyagos#218]
パイプ処理は何か考慮する必要がありますでしょうか。

現状
```
Nihongo Yet Another GOing Shell 4.1.9_3-amd64 by go1.8.1 & Lua 5.3
(c) 2014-2017 NYAOS.ORG <http://www.nyaos.org>
$ dir | find "<DIR>"
FIND: パラメーターの書式が違います
exit status 2
```

期待する動作
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.
c:>dir | find "<DIR>"
2017/05/13  18:02    <DIR>          .
2017/05/13  18:02    <DIR>          ..
```

**Comment by zetamatta** [comment]
特に考慮する必要はないはずですが、ご指摘の現象がこちらでも再現しましたので、何らかの問題が発生していると思われます。調査しますので、少々お時間いただけますでしょうか。

なお、FIND ではなく、FINDSTR ではエラーは出ないようなので、解決するまで暫しそちらで代用いただけますでしょうか

```
$ dir | findstr "<DIR>"
2017/05/13  21:42    <DIR>          .
2017/05/13  21:42    <DIR>          ..
```

よろしくお願いいたします。

**Comment by zetamatta** [comment]
確認したところパイプラインが原因ではなく、「検索文字列は二重引用符で囲まれていなければいけない」とする FIND の引数の仕様にひっかかってエラーになっているようです（だから、そういう条件のない、FINDSTR だとうまく動作する）

NYAGOS はコマンドライン文字列を一度、分解してから、再度構築しているのですが、その過程で一見すると不要に見える二重引用符をとってしまっています。その結果、第一引数が「"<DIR>"」ではなく「<DIR>」で渡されてしまい、検索文字列と見えなくなってしまっているようです。
（なお、CMD.EXE を通していないので、リダイレクトは機能しません）

何かしら対策を検討いたします。

**Comment by zetamatta** [comment]
ユーザが明示した二重引用符を勝手に削除しない修正を最新ソースに行いました。
（今回の場合、`"<DIR>"` が `<DIR>` として渡されていたため、FINDコマンドが`<DIR>`を検索文字列と認識できなくなったという問題が発生していました）

いずれ 4.2.0 に反映されますが、とりあえず、そのソースを元にビルドしたスナップショットの実行ファイルを以下に添付いたします。

- [nyagos-20170514-amd64.zip](https://github.com/zetamatta/nyagos/files/999031/nyagos-20170514-amd64.zip)
- [nyagos-20170514-386.zip](https://github.com/zetamatta/nyagos/files/999030/nyagos-20170514-386.zip)

これらをお試しいただければと思いますが、そこまで手間をかけたくない場合などは現行のバージョンでも、`FIND`コマンドではなく、`FINDSTR`コマンドなどを使えば、期待動作は実現できるかと存じます。

以上、よろしくお願いいたします。

**Comment by zkangaroo** [comment]
早々のご対応ありがとうございます。

> nyagos-20170514-amd64.zip

こちらで期待する動作を確認しましたのでクローズいたします。
