### ISSUE TITLE
Windows 10 Creaters Updateから:Cmder/ConEmu上のnyagosの日本語入力ズレ

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#223]
状況報告です。

表題の問題がありますが、これはCmdの既定値について「従来のコンソールを使う」にすれば、当座回避できます。(CLIの構造をCmd上で制御している、ということになる? ConEmuのTaskとしては直にnyagosを起動している)

これをoffにした時にも適切に対応できるようになると嬉しい、というのはありますが、遠い未来へのfeature request、ということで、まずは情報共有です

> まあ、Cmder/ConEmuが対処してしまうかもですが、レイヤ的に関係する可能性はあるかなと

参考

* http://qiita.com/imidorf/items/309c989aa44d0cd670e8
* https://github.com/cmderdev/cmder/issues/1339

**Comment by zetamatta** [comment]
未検証ですが、KB4020102 にて解消したとの[情報をいただいています](https://twitter.com/shela_/status/868124435244474369)。

* [May 25, 2017—KB4020102 (OS Build 15063.332) - Windows Help](https://support.microsoft.com/en-us/help/4020102/windows-10-update-kb4020102)

これかな？

* Addressed issue where some non-Unicode fonts (Courier, MS Sans Serif, etc.) do not render characters correctly on non-Latin, single-byte system locales (Greek, Hebrew, Arabic, etc.). Black bars or other artifacts appear instead

**Comment by tsuyoshicho** [comment]
こちらでも確認できました。最新のWindows10だと「従来のコンソールを使う」をoffにしても問題ないですね。

ということでなんだかアレですが、クローズでいいかと思います。

**Comment by zetamatta** [comment]
了解です。では、一旦クローズさせていただきます。
