### ISSUE TITLE
同じプリフィクスの exe ファイルが複数あると別ファイルが実行されることがある

### ISSUE THREAD

**Issue by Matsuyanagi** [zetamatta/nyagos#229]
nyagos 4.1.9.3-amd64
Windows10, Windows7
ConEmu 160710

test.cpp
~~~cpp
#include <stdio.h>
#include <stdlib.h>

int main( int argc, char **argv )
{
	puts( argv[ 0 ] );
	return 0;
}
~~~
`cl test.cpp` で作成された test.exe をコピー、リネームして test.456.exe, test.y123.exe を作ります。
違うのはファイル名のみです。

~~~
test.456.exe
test.exe
test.y123.exe
~~~

これらを PATH 環境変数、もしくはカレントディレクトリに置いて `test` を実行すると

> test.456.exe

と表示されます。 test.456.exe が実行されています。

nyagos
~~~
$ test
test.456.exe
$ cmd /c test
test

$ which test
test.456.exe
$ where test
C:\Works\test_exe\test.exe
~~~

cmd.exe では test.exe が実行されるので挙動に差違が出ています。

この問題のみに関しては

\dos\lookpath.go(62)
~~~go
if path := lookPath(dir1, filepath.Join(dir1, name+".*")); path != "" {
~~~
ここで "test.*" を検索して 

\dos\lookpath.go(20)
~~~go
suffix_ := filepath.Ext(f.Name())
~~~
が test.456."exe" にマッチしているらしいのは見当がつきましたが、スマートな解決方法が提案できません。

**Comment by zetamatta** [comment]
ありがとうございます。症状を確認しました。

```console
$ type ahaha.386.cmd
@echo %~f0
<HAYAMA-PC:~/go/src/github.com/zetamatta/nyagos>
$ ahaha
C:\Users\Hayama\go\src\github.com\zetamatta\nyagos\ahaha.386.cmd
```

**Comment by zetamatta** [comment]
若干、泥臭い形となりましたが、修正いたしました。

```
% type ahaha.386.cmd
@echo %~f0
% ahaha
'ahaha' is not recognized as an internal or external command,
operable program or batch file
% ahaha.386
C:\Users\Hayama\go\386-nyagos\ahaha.386.cmd
% ahaha.386.cmd
C:\Users\Hayama\go\386-nyagos\ahaha.386.cmd
% vim
% gvim
%
```
（vim、gvim も %PATH% 上にあるコマンド、ともに起動を確認）

本当は `4.1.9_4` という形が望ましかったのですが、`4_1` ブランチを壊してしまった（`4.2` 向けの修正がいっぱい入ってしまっていて除く作業で返ってエンバグしそう）なので、とりいそぎ、スナップショットという形でバイナリを作成しました。
（4.1系列に致命的な不具合がない限りは、たぶん `4.1.9_x` は作らず、本修正はもう `4.2.0` の方だけに含める形になるかと思います）

一応、amd64、386 両方のバイナリを添付いたしますが、症状をご確認された環境の方で修正を確認いただければ幸いです。

[nyagos-20170524-amd64.zip](https://github.com/zetamatta/nyagos/files/1024324/nyagos-20170524-amd64.zip)
[nyagos-20170524-386.zip](https://github.com/zetamatta/nyagos/files/1024336/nyagos-20170524-386.zip)

よろしくお願いいたします。

**Comment by Matsuyanagi** [comment]
想定通りの動作を確認しました。
~~~
$ ls *.exe
test.456.exe
test.exe
test.y123.exe

$ test
test.exe
$ cmd /c test
test

$ which test
test.exe
$ where test
C:\Works\test_exe\test.exe
~~~

4.2 系で修正されるとのこと了解しました。
手早い対応ありがとうございました。

**Comment by zetamatta** [comment]
4.2.0_0 に本修正を含めましたので、クローズさせていただきます。
