### ISSUE TITLE
リリース4.18.0からlsがカラー表示されない

### ISSUE THREAD

**Issue by maskedw** [zetamatta/nyagos#230]
**[確認環境]**  
Windows 10 Pro バージョン 1607 (OSビルド14393.1198)

表題の通り、リリース4.17.0まではlsコマンドがカラー表示されていたのですが、4.18.0からはされなくなりました。最新の4.20.0でもカラー表示されないことを確認済みです。何か設定が必要になったのでしょうか？

**Comment by zetamatta** [comment]
申し訳ありません。エイリアス定義を `_nyagos` という別の設定ファイルに移動させていたのですが、そちらをパッケージに添付していなかったようです。

本日中に添付したバージョンをリリースしますが、とりあえずカラー化させるためには、`%USERPROFILE%\_nyagos` というファイルを用意してその中に

```
alias "ls=__ls__ -oFh $*"
```

と書いていただければ Ok です。`-o` というオプションがカラー化を指定するオプションで、それをエイリアスで常につくような形となっています。

**Comment by zetamatta** [comment]
[4.2.0_1](https://github.com/zetamatta/nyagos/releases/tag/4.2.0_1) をリリースいたしました。本パッケージに同梱されている `_nyagos` （ドットではなくアンダスコアで始まる方）を %USERPROFILE% か、nyagos.exe と同じフォルダーにコピーいただければ、カラーが復活すると思います。

おそれいりますが、ご確認の程、よろしくお願いいたします。

**Comment by maskedw** [comment]
4.2.0_1でカラー表示がされることを確認しました。ありがとうございます。
