### ISSUE TITLE
内蔵コマンドのsudoについて

### ISSUE THREAD

**Issue by michikora** [zetamatta/nyagos#231]
自分はCmderを使っていまして、sudoする時に新しいウィンドウが開かないように、
内蔵sudoコマンドの代わりに、別途のsudo.exeを使っています。
4.1.8まではluaファイルの中のsudoの部分をコメントアウトすることで内蔵のsudoを無効化していましたが、
4.1.8以降は自分でnyagosをビルドし直すこと以外、ほかに内蔵のsudoコマンドを無効化する方法はないでしょうか？
また、内蔵のsudoコマンド使うとき、新しいウィンドウ開かないようにすることはできるのでしょうか？

**Comment by zetamatta** [comment]
内蔵版を無効にするには、拡張子EXEまで含めてエイリアスを定義していただくのが早いと思われます。

- `~\.nyagos` に `nyagos.alias.sudo="sudo.exe"`

もしくは

- `~\_nyagos` に `alias sudo=sudo.exe`

とすれば Ok です。

    また、内蔵のsudoコマンド使うとき、新しいウィンドウ開かないようにすることはできるのでしょうか？

すみません。現行(4.2.0)の内蔵 sudo では、どうしても新しいウインドウを開いてしまいます。
（sudo.exe が新ウインドウなしで起動されるなら、その方法をまた調べてみたいと思います）

**Comment by michikora** [comment]
ご返答ありがとうございます、無事にsudo.exeのエイリアス定義できました。
内蔵sudoの仕様についての返答もありがとうございます、
ご参考までに、自分は現在使っているsudo.exeはhttps://bitbucket.org/wantora/sudoこちらのものになります。

**Comment by zetamatta** [comment]
おぉ、wantora 先生の sudo ですか。管理者権限で動くプロセスを別に立ち上げて、パイプラインで入出力を接続するという方式ですね。
昔、意味もよく分からずにちょっと触っていたようなんですが、忘却の彼方になっていました。
ありがとうございます。
