### ISSUE TITLE
Support of Alt+BACKSPACE and Alt+"/"

### ISSUE THREAD

**Issue by masamitsu-murase** [zetamatta/nyagos#242]
Alt+BACKSPACE や Alt+"/" のキーバインドに対して bindKey する方法はあるのでしょうか？
現状、どうもサポートされていないようなのですが、将来的にサポートされる予定はありますでしょうか？

上記の二つのキーに関しては、下記のようにすればよいのだと思いますが、最終的にどこまでの仮想キーコードをサポートすべきかなどがよく分からなかったので、pull request にはしませんでした。
https://github.com/masamitsu-murase/nyagos/commit/b70f84acd830c093a0fbeb9b61dfd75e39b29aa4

**Comment by zetamatta** [comment]
サポートする予定はありませんでしたが（というより単に思い至らなかっただけ）、特別難しいというわけでもありませんし、必要とあれば無論実装したいと思います。

どこまでの仮想コードをサポートすべきかについては、自分にもあまりよい考えがないので、まずはとりあえず２キーだけサポートでも問題ないと思います。
（プルリクいただいても結構ですし、こっちで適当に追加でも、どっちでも Ok です）

**Comment by masamitsu-murase** [comment]
了解しました。
それでは pull request を送らせていただきます。

(これを機に tcsh から nyagos に乗り換えます！)

**Comment by zetamatta** [comment]
ありがとうございます！
