### ISSUE TITLE
画面を上にスクロールした状態で、Ctrl キーや Shift キーを押しただけでも、スクロール位置が戻されてしまう。

### ISSUE THREAD

**Issue by masamitsu-murase** [zetamatta/nyagos#251]
Issue かどうか微妙ですが、画面を上方にスクロールした状態で、Alt, Ctrl, Shift などの文字入力を伴わないキーを押した場合でも、スクロール位置が元に戻ってしまいます。

具体的には、スクロールして上の方に流れてしまったテキストを読んでいる際に、Alt+Tab などで別ウィンドウに切り替えようとすると、Alt を押したタイミングで、プロンプト部分まで画面がスクロールしてしまいます。  
(個人的には、上までスクロールした状態のウィンドウを保って、Alt+Tab で他のプログラムに切り替えて作業をしたいので、しばしば困ります。)

原因は、  `readline.go` の `ReadLine` の中のキー待ち部分で、常に CURSOR_ON/CURSOR_OFF を出力しているからのようです。

下記で試しに修正してみたのですが、あまりスマートでないような気もしています。
Go では関数ポインタの比較ができないので、 `KeyFuncPass` を廃止し、nil であれば `KeyFuncPass` 相当であるというようにしてみました。

https://github.com/masamitsu-murase/nyagos/commit/4d6bff7d17a99499b1a34c486fd5977d564e9368

「このように書くべし」などありましたら、お教えいただけると幸いです。

**Comment by zetamatta** [comment]
ありがとうございます。ご提示いただいたコードで Ok だと思います。
こちらでの動作確認は済んでいますので、プルリクいただければ、すぐマージします。

* 最初、カーソルの視認性を気にしていましたが、特に問題ないことを確認しました。
* また、Ctrl や Shift を押下した時に、スクロールが戻るという現象が解消されている点も確認しました。

「何もしない関数」を廃止して、nil で特別扱いするのは、確かにやむをえないと考えられます。キーの処理関数を実行した後の例外的な処理ならば、関数の戻り値（CONTINUE,ABORT…）の種類を増やせばどうにもなりますが、関数を呼ぶ前の例外的な処理（カーソルオフを実行しない）は無理ですし、仕方ないかと思います。

**Comment by masamitsu-murase** [comment]
承知いたしました。
ご確認ありがとうございます。
pull request させていただきました。

**Comment by zetamatta** [comment]
先ほど merge いたしました。ありがとうございます
