### ISSUE TITLE
nyagos-4.2.2_0-386 が64bitでビルドされている

### ISSUE THREAD

**Issue by hazychill** [zetamatta/nyagos#253]
[nyagos-4.2.2_0-386](https://github.com/zetamatta/nyagos/releases/tag/4.2.2_0) が64bitとしてビルドされているようで、32bit OSでは起動できませんでした。

$ file ./nyagos-4.2.1_0-386/nyagos.exe
./nyagos-4.2.1_0-386/nyagos.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows

$ file ./nyagos-4.2.2_0-386/nyagos.exe
./nyagos-4.2.2_0-386/nyagos.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows

ビルド環境がないので検証できていませんが、[make.ps1](https://github.com/zetamatta/nyagos/blob/d1a9b4d41b886ab87a72613a9f8163caf09c378e/make.ps1#L177) にあったGOARCHの設定が [make.cmd](https://github.com/zetamatta/nyagos/blob/c70a6f1e4fc6332f0bb7086a107795b1c985ee8b/make.cmd#L178) でなくなっているのが原因でしょうか。

**Comment by zetamatta** [comment]
ご指摘、ありがとうございます。make.cmd と make.ps1 を差し替えた時、GOARCH まわりの修正が消えてしまったようです（多分、ブランチを切り替えている間の事故かと）

とりいそぎ、GOARCH まわりの修正を復活させた上で、バイナリを作り直しました。

https://github.com/zetamatta/nyagos/releases/tag/4.2.2_1

よろしくお願いいたします。
