### ISSUE TITLE
提案 : grepのスマート化

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#293]
nyagosでのgrepなのですが、以下のようにするのはどうでしょう?

```lua
-- in comspec.lua

local greppath=nyagos.which("grep.exe")
if not greppath then
  nyagos.alias.grep = "findstr.exe"
else
  nyagos.alias.grep = "grep.exe"
end
nyagos.alias.findstr = "findstr.exe"
```

Git for Winなど、grepを持ってる人にはgrep=findstrエイリアスは微妙ということもあるかなと。
ただ、オプションが環境で変ってしまう、という副作用があるのですが...
その辺を避けるなら、findstrを直に使い、最低限の互換性的なものは保障される感じです。

**Comment by zetamatta** [comment]
ありがとうございます。ご指摘いただいて、`nyagos.alias.grep="findstr.exe"` の alias は失敗だったと思いました。自分も grep どの検索プログラムが動くか分からないと混乱するので、結局現在では findstr.exe を使う時は findstr と明示的にタイプしています。

それで対応方法ですが、ご提示のように、grep が見つからない時だけ grep = "findstr.exe" としてもいいですし、あるいは、シンプルに「`nyagos.alias.grep="findstr.exe"`」という行を消すだけとしてもいいかもしれません。（どないしましょうかね…）

**Comment by spiegel-im-spiegel** [comment]
「シンプルに「nyagos.alias.grep="findstr.exe"」という行を消す」に1票です。

私は jvgrep を grep として alias を上書きして使ってます。標準 grep が Windows にないのは仕方がないので，もう好きなものを自分で定義して使うでいいじゃないでしょうか。

**Comment by zetamatta** [comment]
判断に迷ったのですが「あるはずの grep.exe が使えない」という現状の放置はよくないので、とりあえず tsuyoshicho さんご提示のものをちょっと変えた形で組み込みました。

ただ、この方式でも、`%USERPROFILE%\.nyagos` の中で「後から」追加した %PATH% の中に grep.exe があった場合などまでは対応できないので、本当は削除した方がよいのだろうと思います。
（ただ、過去バージョンとの互換性というキーワードには弱いので…今回のところは問題先送りです）

**Comment by tsuyoshicho** [comment]
少し返事が遅れましたが、対応ありがとうございます。

**Comment by zetamatta** [comment]
ありがとうございます。一旦クローズさせていただきます。
