### ISSUE TITLE
NYAGOS 4.2.5_beta でバッチファイルがエラーになります。

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zetamatta/nyagos#296]
日本語ご容赦です。
以下のバッチファイルを 4.2.5_beta 上で実行するとバッチ処理完了後にエラーになります。

```
@echo off
setlocal

setlocal enabledelayedexpansion

set /a n = %~1
set /a b1 = 0
set /a b2 = 0

if %n% == 1 echo 1: %b2% && goto :end
echo 1: %b2%
set /a b2 = 1
if %n% == 2 echo 2: %b2% && goto :end
echo 2: %b2%
for /l %%i in (3, 1, %n%) do (
	set /a fib = !b1! + !b2!
	set /a b1 = !b2!
	set /a b2 = !fib!
	echo %%i: !b2!
)

:end
endlocal && set /a fib = %b2%

echo %~1th Fibonacci number is %fib%
endlocal
```

エラー内容はこんな感じです。

```
$ fibonacci.cmd 10
1: 0
2: 1
3: 1
4: 2
5: 3
6: 5
7: 8
8: 13
9: 21
10: 34
10th Fibonacci number is 34
't' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'd' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
指定されたパスが見つかりません。
open C:\Users\userbame\AppData\Local\Temp\nyagos-6296.tmp: The system cannot find the file specified.
```

ちょっと意地悪なコードかなぁという気もしますが，報告まで。

**Comment by zetamatta** [comment]
ご報告ありがとうございます。ですが、どうもこちらではうまく再現できません。

```
$ .\nyagos
Nihongo Yet Another GOing Shell 4.2.5_beta-amd64 by go1.10 & Lua 5.3
(c) 2014-2018 NYAOS.ORG <http://www.nyaos.org>
<DESKTOP-LGGUCRA:~/tmp>
% fibonacci.cmd 10
1: 0
2: 1
3: 1
4: 2
5: 3
6: 5
7: 8
8: 13
9: 21
10: 34
10th Fibonacci number is 34
<DESKTOP-LGGUCRA:~/tmp>
```

ただ、お見せいただいた出力を見る分では、パラメータの引き渡しに失敗しているように見えます（引数中に改行コードか何かが入っている？）

お手数ですが、fibonacci.cmd のあるフォルダーで「`source -d fibonacci.cmd 10`」を実行してみてから、`%TEMP%` にある更新日時が最も新しい `nyagos-*****.cmd` の中身を見せていただけないでしょうか。

本来であれば、

```nyagos-13020.cmd
@call C:\Users\hymko\Share\bin\fibonacci.cmd 10
@set "ERRORLEVEL_=%ERRORLEVEL%"
@(cd & set) > "C:\Users\hymko\AppData\Local\Temp\nyagos-13020.tmp"
@exit /b "%ERRORLEVEL_%"
```

といったファイルになっているはずですが、最初の行がおかしくなっている可能性が高いと見ています。

よろしくお願いいたします。

**Comment by zetamatta** [comment]
（参考）別件の不具合を確認・修正しました。

- [On 4.2.5_beta, running the batchfile includes `exit` without `/b` option, an error occurs. · Issue #297 · zetamatta/nyagos](https://github.com/zetamatta/nyagos/issues/297)

バッチファイル中に「`exit`」が /b オプションなしで実行すると、`nyagos-****.cmd` もひっくるめて CMD.EXE が即終了してしまうため、環境変数の内容が出力されないというものでした。

この手のバッチファイルは CMD.EXE 単体でも環境変数の読み込みができないため、今回はエラーメッセージを

```
C:\Users\hymko\ex.cmd: the batch file may use `exit` without `/b` option. Could not find the change of the environment variables
```

に変更するだけに留めました。

**Comment by spiegel-im-spiegel** [comment]
実はこれを試したマシンは Windows アカウント名が漢字になってまして，上の手順でできてる `nyagos-*****.cmd` の中身も

```
@call fibonacci.cmd 10
@set "ERRORLEVEL_=%ERRORLEVEL%"
@(cd & set) > "C:\Users\漢字の~2\AppData\Local\Temp\nyagos-5312.tmp"
@exit /b "%ERRORLEVEL_%"
```

みたいな感じになってました（アカウント名は置き換えてます）。この辺が理由でしょうか。

ちなみにアルファベットのみのアカウント名ではうまくいきました。

**Comment by spiegel-im-spiegel** [comment]
続きです。

環境変数を見ると `USERPROFILE` は

```
USERPROFILE=C:\Users\漢字のユーザ名
```

となっているのに `TEMP`, `TMP` は

```
TEMP=C:\Users\漢字の~2\AppData\Local\Temp
TMP=C:\Users\漢字の~2\AppData\Local\Temp
```

と短縮名になってるようです。設定側はどちらも

```
%USERPROFILE%\AppData\Local\Temp
```

なんですけどねぇ。ちなみに Windows 8.1 です。

**Comment by zetamatta** [comment]
ありがとうございます。すばらしいエラーリポートです。
この手の問題に遭遇した人は「使えない」という烙印だけ押して、だいたい消えてしまうんですよね。
たすかります！

**Comment by zetamatta** [comment]
2点問題がありました。

1.  一時ファイルのパスが、現在のコードページ文字列（ANSI / CP932）ではなく、UTF8 で出力されていた。
2.  一時バッチファイルの改行コードが CRLF ではなく、LF になっていた。

これらを修正したところ「漢字のユーザ名」という名前ユーザでも、期待動作するようになりました。

不思議なことに、1. を直しただけで直りそうなものなのですが、なぜか 2. も合わせて修正しないと直りませんでした。であれば、なぜ英数字だけのユーザ名ではちゃんと動いていたのか…それが謎です。

ソースは 876a453 にて修正済みですが、そのうちバイナリも beta2 としてリリースしたいと思います。

**Comment by zetamatta** [comment]
以上を反映したバイナリ: [4.2.5_beta2](https://github.com/zetamatta/nyagos/releases/tag/4.2.5_beta2) を公開しました。

**Comment by spiegel-im-spiegel** [comment]
4.2.5_beta2 を使って同環境で確認しました。問題ありません。
`source -d` を使って試してもみましたが出力されているファイルの内容も問題なさそうです。

素早い対応，ありがとうございました。

**Comment by zetamatta** [comment]
動作確認ありがとうございました。

自分の環境だけでは気づけない問題があるので、たいへん、たすかりました。beta を出した甲斐があったというものです。もうしばらくだけ使って、特に問題ないようであれば、`4.2.5_0` としてリリースしたいと思います。

それでは本件については、クローズさせていただきます。
