### ISSUE TITLE
--look-curdir-never was not working as expected

### ISSUE THREAD

**Issue by zetamatta** [zetamatta/nyagos#316]
(Japanese title:  --look-curdir-never が期待どおり機能していない

http://text.baldanders.info/release/2018/06/nyagos-4_3_1-is-released/

**Comment by zetamatta** [comment]
The problem is not found in Windows7 machine. I will try to test on Windows10 tomorrow.

![image](https://user-images.githubusercontent.com/3752189/41136117-ccb5ca4e-6b0f-11e8-80f0-41105fdac3e0.png)

**Comment by tyochiai** [comment]
on Windows 10 (1709)

![win10](https://user-images.githubusercontent.com/363199/41161064-78b17922-6b6c-11e8-93a4-104609ee3802.png)

**Comment by zetamatta** [comment]
(自宅の Windows10 では再現しなかったので、何か、他に要因があるのかもしれません。引き続き、調査します。)

**Comment by tyochiai** [comment]
PATH の最後が ; だと dos.LookPath() の dir1 が "" になって、name と Join した結果の "tst_lookcurdir.exe" が見つかって実行されるような気がしました。
（プチ修羅場につき投げっぱなしですみません）

**Comment by zetamatta** [comment]
ありがとうございます。「`set PATH=%PATH%;`」実行後に試してみたところ再現しましたので、どうやら、そのケースのようです。

**Comment by zetamatta** [comment]
空のエントリが入っていても、カレントディレクトリとみなさないようにしました。これで --look-curdir-never も期待どおり機能する（カレントディレクトリの実行ファイルは `%PATH%` に「`.`」が入ってない限り無視する）はずです。

反映スナップショット → [nyagos 1.0.926 - AppVeyor](https://ci.appveyor.com/project/zetamatta/nyagos/build/1.0.926/job/pck7ujspxwns4btx/artifacts)

**Comment by tyochiai** [comment]
こちらでも上記の反映スナップショットでは期待通りカレントディレクトリの exe が実行されないことを確認しました。

**Comment by zetamatta** [comment]
本修正を反映した [4.3.1_3](https://github.com/zetamatta/nyagos/releases/tag/4.3.1_3)をリリースしました

**Comment by tsuyoshicho** [comment]
>  4.3.1_3-amd64 by go1.10.3

関連不明ですが、`;;`が含まれる環境でときどきPATHの解決ができなくなることがありました。
再起動(再ログイン?)すると回復したりします。

現在は`;;`を見付けて、影響不明ながら除去し、再発はしていないです。

もし影響がなくて再発したら、別にissueを上げます。
(実験的に`;;`を入れて再発と解析を狙うべきかもしれませんが...)
