### ISSUE TITLE
Problem : rlcone subcomplete expand is locked

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#317]
nyagos.d/catalog/subcomplete.lua
のrcloneの展開処理なのですが、処理が詰ってしまい、起動しない(ctrl-cしないといけない)となりました。

コメントアウトすると大丈夫なので、そこに問題はありそうです。
原因究明が後に回るなら、一旦コメントアウトしてしまってもよいかもしれません。

```
Nihongo Yet Another GOing Shell 4.3.1_0-amd64 by go1.10.2
```

Windows 10 Pro 1803

**Comment by zetamatta** [comment]
どうも、デッドロックが発生しているようです。
io.popen ＆ lines で読まずに捨てるテキストの量が多い場合に発生する問題のようです。

* rclone.exe はパイプラインのバッファが満タンになって出力できないので、バッファに空きが出来て出力できるのを待っている
* subcomplete.lua では、途中で読みだしループを中断して、close() を試みている
* close 関数では rclone.exe の終了を待っているが、rclone も待っているので、永遠にお見合いが続いてしまう

nyagos だけでなく、オリジナルの GopherLua でも発生しましたので、ライブラリ側にリポートを出すとともに、nyagos は nyagos でスクリプト側に問題回避の修正を入れます。

**Comment by zetamatta** [comment]
再現ソース (glua.exe でも再現する)
[popen_and_break.lua.txt](https://github.com/zetamatta/nyagos/files/2087911/popen_and_break.lua.txt)

**Comment by zetamatta** [comment]
[Try to fix 317: rlcone subcomplete expand is locked](3116fc12e79b80bdf9844e3bb3c664deaca9d5ca)

**Comment by tsuyoshicho** [comment]
了解です、ありがとうございます。

**Comment by zetamatta** [comment]
本修正を反映した 4.3.1_1 のバイナリを公開しました。
https://github.com/zetamatta/nyagos/releases/tag/4.3.1_1

**Comment by tsuyoshicho** [comment]
4.3.1_1 で正常に起動すること、rcloneのsubcompleteできることを確認しました。(ただ別件はあります)
