### ISSUE TITLE
4.3.1_1 complettion args fail

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#320]
以下の環境でサブコマンド補完時に挙動がおかしいです。

```shell-session
Nihongo Yet Another GOing Shell 4.3.1_1-amd64 by go1.10.3 Powered by GopherLua 0.1
```

Windows 10 Pro 1803

症状ですが、

```
$ rclone listremotes
exec: "map[rawargs:map[1:listremotes 0:rclone] 0:rclone 1:--ask-password=false 2:listremotes]": file does not exist
$
```

`listremotes` という補完は効きます。ただ実行時にエラーします。

おそらく、次のaliasが悪さをしています。

```lua
-- alias
nyagos.alias.rclone = function(args)
  -- password detect
  local password = ''
  password = nyagos.eval('gpg --no-verbose --quiet --batch --decrypt --output - ~\\.password-store\\Storage\\Rclone.gpg 2> nul')
  nyagos.env["RCLONE_CONFIG_PASS"] = password
  table.insert(args,1,'--ask-password=false') -- prompt off
  assert(nyagos.rawexec(args))
end
```

table.insertした結果が内部にとって意図しないものになっているのでしょうか?
それともトリッキーなrcloneの定義がうまく扱えないのでしょうか? 以前はrcloneのaliasとしてrclone.exeを呼べていたのですが...

これもLua5.3互換問題かもしれませんので、症状の報告まで。

**Comment by zetamatta** [comment]
確認したのですが、nyagos.rawexec はパラメータにテーブルはとらないので[※](https://github.com/zetamatta/nyagos/blob/master/Doc/07-LuaFunctions_ja.md#errorlevelerrormessage--nyagosrawexec%E5%A4%96%E9%83%A8%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E5%90%8D%E5%BC%95%E6%95%B01%E5%BC%95%E6%95%B02)

```lua
nyagos.alias.rclone = function(args)
    assert( nyagos.rawexec(args) )
end
```

は動作しなくて正解なのですが、4.2.5 だと動いちゃいますね…なぜだろう

**Comment by tsuyoshicho** [comment]
あれ....? そもそもどこか他のところのを参照にはしてたんですが。
見直したら、たぶん `nyagos/nyagos.d/catalog/gogit.lua`の

```lua
nyagos.alias.go = function(args)
    if #args >= 1 and git_only[args[1]] then
        args[0] = "git" 
    else
        args[0] = "go"
    end
    assert(nyagos.rawexec(args))
end
```

とあるので、このへんかな?

ドキュメントを見直すと、たしかに可変長というだけですね。手元の修正は考えてみます。

> 意図としては
> 1. rclone.exeの補完を活用しつつ
> 2. aliasを呼び出し(.exeがないので)で内部で引数と環境変数を補充して実行実施
>
> したいということなので、順序がちょっと面倒ですね...
> `nyagos/nyagos.d/aliases.lua`の `nyagos.rawexec(args[0],(table.unpack or unpack)(args))`を参考にするといいかな?

ありがとうございます。

**Comment by zetamatta** [comment]
4.2.5 では「パラメータの要素の中にテーブルがあれば、それの中身を展開する仕組み」を nyagos.rawexec で呼び出していたようですが、4.3 ではそれが移植されていなかったようです。

**Comment by zetamatta** [comment]
移植漏れになりますので、こちら (nyagos.exe) の方を修正します。少々お待ちください

**Comment by tsuyoshicho** [comment]
はい、了解です。

**Comment by zetamatta** [comment]
修正したバイナリ 4.3.1_2 をリリースしました。
https://github.com/zetamatta/nyagos/releases/tag/4.3.1_2

nyagos.rawexec だけでなく、nyagos.raweval も同様の非互換性があったため、あわせて修正しました。

**Comment by tsuyoshicho** [comment]
帰ったら試してみます

**Comment by tsuyoshicho** [comment]
修正されていることを確認できました。問題ありませんでした。
