### ISSUE TITLE
ドキュメントの機能名が更新されていない

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#321]
`HISTORY_DOWN`と`NEXT_HISTORY`など
変更された機能名がドキュメントに反映されていないものがあります。

https://github.com/zetamatta/nyagos/blob/master/Doc/04-Commands_ja.md#bindkey-キー名-機能名
https://github.com/zetamatta/nyagos/blob/master/readline/constants.go#L105

記載順がわからなかったのでPRではなくissueに上げさせていただきました。

**Comment by zetamatta** [comment]
ありがとうございます。経緯を確認しました。

- ドキュメントの修正 → 40bacf28fddb80001069eec1542716840cad3432 (11 Oct 2014)
- ヒストリ機能のキーアサインの実装 → 1df2baf7 (4 Jan 2015)

どうも機能名が当時二転三転していたようです。bash と同じ機能名「next-history」「previous-history」に変えようとしたが、うっかり元に戻してしまったのかもしれません？

ドキュメントが「正」なので、ドキュメントどおり実装を直すが、互換性のために「history-down」「history-up」も使えるようにしておきたいと思います。

**Comment by zetamatta** [comment]
4種類の機能名全て使えるようにしました。

```lua
nyagos.key.f1 = "next-history"
nyagos.key.f2 = "previous-history"
nyagos.key.f3 = "history-down"
nyagos.key.f4 = "history-up"
```

最新バイナリ（スナップショット）は [nyagos 1.0.926 - AppVeyor](https://ci.appveyor.com/project/zetamatta/nyagos/build/1.0.926/job/pck7ujspxwns4btx/artifacts)よりダウンロードできますが、そのうち、修正版も出す予定です。

**Comment by zetamatta** [comment]
本修正を反映した [4.3.1_3](https://github.com/zetamatta/nyagos/releases/tag/4.3.1_3)をリリースしました
