### ISSUE TITLE
problem : batchfile arg UTF-8 data broken.

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#322]
```
Nihongo Yet Another GOing Shell 4.3.1_2-amd64 by go1.10.3
Powered by GopherLua 0.1
(c) 2014-2018 NYAOS.ORG <http://www.nyaos.org>
```

Windows 10 Pro 1803

バッチファイル実行で問題があります。
以前は大丈夫だったように見うけます。

次のようなバッチファイル

```batchfile:testbat.bat
REM @echo off
echo %*
echo %* > testbat.txt
echo save data
```

を使って、以下の処理

```shell-session
$ ./testbat.bat "テスト"
```

を行い、ファイルを見ると

```text
"???" 
```

となってしまいます。(画面表示も)

このバッチファイルはコマンドプロンプトから直に実施する分には問題ないことも確認できています。
> これの元になったバッチファイルでも同じ動作になります。

なお、nyagosはConEmuで利用しており、

```
chcp 65001 & C:\tools\nyagos\amd64\nyagos.exe -new_console
```

としてコードをUTF-8に設定しています。

**Comment by zetamatta** [comment]
どうも、現在の最新のコードページを拾えていないようです。
一時バッチファイルの中身に出力している引数が CP932 のままになっていました。

**Comment by zetamatta** [comment]
スレッドのコードページ(`CP_THREAD_ACP`)を使っていたのですが、これは間違いで、コンソールのコードページ(`GetConsoleCP()`の結果)を使うべきだったようです。

**Comment by zetamatta** [comment]
修正版のバイナリ（スナップショット）が下記からダウンロードできると思いますので、これでお試しいただけますでしょうか ＞@tsuyoshicho 

[nyagos 1.0.924 - AppVeyor](https://ci.appveyor.com/project/zetamatta/nyagos/build/1.0.924/job/skbb1das14iww1ft/artifacts)

**Comment by tsuyoshicho** [comment]
確認しました。

現在環境+`Nihongo Yet Another GOing Shell 4.3.1_2-20-g9d5f087-amd64 by go1.10`で問題なく処理できています。

**Comment by zetamatta** [comment]
@tsuyoshicho ありがとうございます。別件もありますので、それらをまとめたうえで、4.3.1_3としてリリースしたいと思います。
