### ISSUE TITLE
sourceコマンドの実行時に二重引用符が無視される?

### ISSUE THREAD

**Issue by tignear** [zetamatta/nyagos#325]
```source "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"```
とすると
```
'C:\Program' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
exit status 1
```
となるのに対して
```source C:\Progra~2\Micros~2\2017\Community\Common7\Tools\VsDevCmd.bat```
とすれば成功します。
(8.3形式の部分は環境依存)
```source -d "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"```してみると
```
@call C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat
@set "ERRORLEVEL_=%ERRORLEVEL%"
@(cd & set) > "C:\Users\tignear\AppData\Local\Temp\nyagos-6876.tmp"
@exit /b "%ERRORLEVEL_%"
```
となっていました。

**Comment by zetamatta** [comment]
バグリポートありがとうございます。

4.2.5 になった時、source キーワードがなくとも、バッチファイルでの環境変数の変更を CMD.EXE と同じように自動で取り込むようにしました。その際、バッチファイルの直接実行とsource経由の実行のコードを統合したのですが、後者での引数引き渡し処理でエンバグしてしまっていたようです。

（ぶっちゃけると、source が不要になってしまったので、source のテストが雑になってしまった点は否めません。何となくですが、当時、引用符の件わかっていたけれども、sourceの重要性が下がっていたので後回しにしたまま、そのまま忘れてしまった…ような気がします）

問題の引き渡し方法を修正いたしましたので、ご確認いただけますでしょうか。

[こちら](https://ci.appveyor.com/project/zetamatta/nyagos) より、amd64 or i386 → ARTIFACTS を選んでいただくと、自動ビルドされたバイナリがダウンロードできます。

**Comment by tignear** [comment]
動きました。
