### ISSUE TITLE
io.open() with w+ mode

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zetamatta/nyagos#332]
日本語ですみません。

4.3.2_0 以降で nyagos を使って lua スクリプトを実行する際に io.open() 関数を "w+" モードで起動するとサポートされていない旨のエラーになります。また "w" モードにするとエラーにはなりませんが何も書き込まれないように見えます。

この辺の情報が何かないでしょうか。

**Comment by zetamatta** [comment]
（日本語 Ok です）

"w+" がサポートされていないエラーになるのは、完全に手抜きです。すみません。

"w" の方は意図通り書き込まれないでしょうか？手元では以下のように動くのですが…

![image](https://user-images.githubusercontent.com/3752189/44295106-16df3880-a2dd-11e8-9045-51fcd92fa651.png)

可能性としては、わたくしが仕様を間違えたか…あるいは「バッファリングが効いていて、クローズされるまで実際に書き出されない」などの動作のためかもしれません。
（いろいろと手抜き過ぎたかもしれません。申し訳ありません）

**Comment by spiegel-im-spiegel** [comment]
ありがとうございます。

"w" モードについては，ご指摘の通り fd:close() が抜けていて書き込みがちゃんとフラッシュされていないのが原因だったようです。

手持ちのスクリプトでは "w" モードで問題ないようなので，こちらでいきます。
情報ありがとうございました。

**Comment by zetamatta** [comment]
ご報告ありがとうございます。
本 issue ですが "w+" の実装が終わってから close したいと思います。
また、"w" の仕様の方も再検討します（→ なるべくオリジナルに近くなるようにします）

**Comment by zetamatta** [comment]
[(#369) & (#332): Rewrite iolib for Lua & implement r+ and w+ modes · zetamatta/nyagos@f2fc1f0](https://github.com/zetamatta/nyagos/commit/f2fc1f0bfce2f3824a4a214d7df78ce3dc581d75)にて w+ モードを実装しました。

**Comment by zetamatta** [comment]
修正を反映したバイナリ 4.4.4_0 を公開しました。
https://github.com/zetamatta/nyagos/releases/tag/4.4.4_0
