### ISSUE TITLE
Is there a way to increase the number of entries in the history ?

### ISSUE THREAD

**Issue by crile** [zetamatta/nyagos#340]
Hi,

It is not a bug, maybe a feature request. 
Can I increase the number of entries in the history ?
I don't find it in the documentation

Thanks

**Comment by zetamatta** [comment]
Sorry, the number of entries can not be changed **now**. It is defined as `const max_histories = 1000` in the source file.

But, in the next version, I can make some command to change the number of entries.

**Comment by zetamatta** [comment]
I made the new lua variable `nyagos.histsize`. If you write `nyagos.histsize = 2000` in `.nyagos` and restart nyagos, nyagos.exe keeps 2000 entries at least.

The next version of nyagos.exe includes this change. If you want to try to use, you can download the snapshot from these URL.

* 64bit   
 https://ci.appveyor.com/project/zetamatta/nyagos/builds/20575817/job/jp2kk76j3bpw1a2m/artifacts
* 32bit  
  https://ci.appveyor.com/project/zetamatta/nyagos/builds/20575817/job/ramkti01tfh70xpl/artifacts

**Comment by crile** [comment]
Thanks a lot for your quick answer and fix.
I currently test the new build. 
I set the parameter to `2000`. Before I closing _nyagos_, there are more than `2100` lines in the history.
After restart _nyagos_, there are only `1700` lines in the history. 
However, I flood _nyagos_ with commands to fill the history quickly. Maybe it has some impact.
And if I understand properly, your fix doesn't change the history mechanism.
So, it seems good to me.

Thanks again.

**Comment by zetamatta** [comment]
> there are only 1700 lines in the history.

Duplicated entries may be removed.
But, even if entries are duplicated, the directories and times where/when entries were executed, differ.
(nyagos' history records time and directory)
So, I shoud fix to make entries not removed.

Please wait a moment !
