### ISSUE TITLE
"2>&1" 標準エラー出力を標準出力へリダイレクトすると画面出力がおかしくなる

### ISSUE THREAD

**Issue by Matsuyanagi** [zetamatta/nyagos#347]
OS : Windows10 Home
nyagos : 
  4.3.3_4-amd64
  4.3.3_3-amd64
  4.3.1_0-amd64
  4.2.5_1-amd64

`dir 2>&1` のように "2>&1" と標準エラー出力を標準出力へリダイレクトすると、そのコマンドの実行以降、次のプロンプトが表示されません。

一見入力を受けつけていないように見えるのですが、`a[Enter]` のように入力すると
```
'a' is not recognized as an internal or external command,
operable program or batch file
```
と出力されます。

`dir[Enter]` と入力すると
```
ディスクに十分な空き領域がありません。
exit status 255
```
と出力されます

`exit[Enter]` と入力すると nyagos を抜けて起動した cmd へ戻ります。

推測ですが、標準エラー出力に表示されるものだけが画面に表示されているようです。
nyagos のバージョンを変えていくつか試してみましたが同様のようです。

`dir 2>nul` のような実行では普通にそのまま動作しています。

**Comment by zetamatta** [comment]
こちらでも再現しました。確認します。

**Comment by zetamatta** [comment]
ご報告ありがとうございます。

リダイレクトがあった時、その入出力先を要クローズ先リストに入れる処理があるのですが、そこで`2>&1` の「`1`」（標準出力）まで要クローズリストに入れてしまっていたようです。
`2>&1` は、たいていの場合「`>filename 2>&1`」という組み合わせで使われていたため、`filename` が２回クローズされる形になって表面化していなかったようです。
（本当は２回クローズされるのも十分まずいのですが）

対応として、`2>&1` などクローズしてはいけない既存入出力先へリダイレクトする際は、要クローズリストに「クローズするフリだけをするダミー」を代わりに放り込んで、クローズさせないしないようにしました。
これで「`dir 2>&1`」を行って、何も表示されなくなる問題は解消されたと思います。

修正バイナリ（スナップショット）は以下よりダウンロード可能です。

* [nyagos-amd64-1.0.1086](https://ci.appveyor.com/project/zetamatta/nyagos/builds/21113589/job/cnte7n3pw9bgid8c/artifacts)

これ、結構、致命的な不具合なので、年内に 4.3.3_5 として改めて修正版を出しておきたいと思います。

**Comment by Matsuyanagi** [comment]
`nyagos-amd64-1.0.1086` で修正されていることを確認しました。

自分も `>filename 2>&1` をやろうとして試していたところでした。

素早い対応ありがとうございました。
