### ISSUE TITLE
ls 後マウスのスクロールが効きにくくなる

### ISSUE THREAD

**Issue by tyochiai** [zetamatta/nyagos#348]
- Version: 4.3.3_4-7-gf3c2cd81-amd64 by go1.11.4
- OS: Windows 10 (1809)

ビルトインコマンドの ls を実行後、マウスの中ボタンでのスクロールがほぼ効かなくなります。
「ほぼ」の通り、がんばって回すとたまに動きます。

Releases のバイナリで確認したところ、4.3.3_4 ではこの現象が起き 4.3.3_3 では起きませんでした。
ただし git で 4.3.3_3 をチェックアウトして make.cmd したバイナリでは起きるため、
おそらく github.com/zetamatta/nyagos の外の変更によるものと思われます。

**Comment by zetamatta** [comment]
確かに。こちらの手元で試したところ、条件は違うのですが、develop branch だとスクロールするのに、master branch (4.3.3_4+アルファ)だと動かなくなるといった状況でした（ともに手元でリビルド）

develop は「子プロセス終了のための Ctrl-C がたまに効かない」という別件の問題に対処するために、コンソールのモードの Set/Reset のコード([SetConsoleMode](https://msdn.microsoft.com/ja-jp/library/cc429744.aspx?f=255&MSPPError=-2147217396))を足しているのですが、それが問題の発生を抑制しているのかもしれません。

同じようなコードを足したら解消するか、いろいろ試してみます。(4.3.3_5 を出す前でよかった)

**Comment by zetamatta** [comment]
@tyochiai すみません。ちょっとコレ試してみていただけますでしょうか

- [nyagos 1.0.1089 (amd64)](https://ci.appveyor.com/project/zetamatta/nyagos/builds/21199785/job/cpfajh49yc7e5xuw/artifacts)

一文字入力に使っているライブラリの [zetamatta/go-getch](https://github.com/zetamatta/go-getch) で[コンソールのマウスイベントを拾わないように修正](https://github.com/zetamatta/go-getch/commit/31a2298565def4bf21ffa66c38929a3298db0625)したところ、スクロールが効くようになりました。が、マウスイベント自体は2017年時点のコードで既に拾うようになっていたので、ここ最近動かなくなった原因はまた別にあるのではないかと思われます。（気持ち悪い状況ですが…）

余談ですが、最近 Windows10 、コンソールまわりがいろいろと変えられているせいか、前には見なかった問題がいろいろと出てきていたりします（MSのバグというわけではないが、未定義の挙動の振る舞いが変わっている的な）。本件も何かそういう類のものかもしれません。

**Comment by zetamatta** [comment]
では、近日中（今日～明日かな）に、修正版を正式リリースします。ありがとうございました。

**Comment by zetamatta** [comment]
こちらへの報告を忘れていました。4.3.3_5 にて反映済みです。
https://github.com/zetamatta/nyagos/releases/tag/4.3.3_5
