### ISSUE TITLE
box.lua のコマンドが動かない

### ISSUE THREAD

**Issue by fushihara** [zetamatta/nyagos#354]
Ctrl+X → h の、cd history が動いていません。
https://github.com/zetamatta/nyagos/blob/e8eaa5f7a46d88a7c10fd24d7284c2cc3f916b4e/nyagos.d/box.lua#L68

↑この行、ch == 'h' ですが c == 'h'の間違いかなと思います。
自分の環境ではこの修正で正常に動きました。

**Comment by zetamatta** [comment]
ご指摘ありがとうございます。修正しました。

**Comment by zetamatta** [comment]
修正版のバイナリ 4.4.1_0 をリリースしました。
