### ISSUE TITLE
type コマンドが上手く働かない

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zetamatta/nyagos#356]
リリースされたばっかりで申し訳ないですが，表題の通り type コマンドが上手く働かないことがあります。具体的には

```
$ type sample.txt
```

でファイルの中身を標準出力に出す場合，テキストの中身が

```
foo
bar
```

で，最後の行が改行で終わらない場合にその行が出力されません。 flush されない感じ？

実は前のバージョンから気付いていたのですが（改行のないテキストが出力されなかった），リダイレクト関連の問題かと勘違いしていて，リダイレクト関連の issue は上がってたのでそのままにしていました。

ちょっとコードの中身を見る余裕が無いので現象の指摘だけですが，参考にしていただけると助かります。

**Comment by zetamatta** [comment]
ありがとうございます。[文字コード変換しているパッケージ](https://github.com/zetamatta/go-texts)の方で、err == io.EOF のとき即ループを終了していたのですが、最後の行の LF がない場合、その行で io.EOF が検出されてしまって終了してしまい、最終行が得られないという不具合がありました。

ということで、go-texts パッケージの方を[修正](9d8b8fe122afff0c0e1e72befedbb1987b42ebc5)しました。

**Comment by zetamatta** [comment]
こちらのバイナリに修正が反映されていると思います。

(amd64) https://ci.appveyor.com/project/zetamatta/nyagos/builds/22085841/job/96o8y4bautern5wn/artifacts
(386)
https://ci.appveyor.com/project/zetamatta/nyagos/builds/22085841/job/b6pw6t5di4dv1jkt/artifacts

**Comment by spiegel-im-spiegel** [comment]
確認しました。問題なく動いていると思います。ありがとうございます。

**Comment by zetamatta** [comment]
ご確認、ありがとうございます。
