### ISSUE TITLE
[regression] AltGR issue

### ISSUE THREAD

**Issue by crile** [zetamatta/nyagos#357]
Hi,

On a french keyboard, to type a pipe, we do `AltGR+6`. In the version 4.3.3_5, everything works fine.
But in the later version, this character appears `^[|`.

It seems that it is some special character because It can't be erased properly.

I try to use `CTRL+ALT+6`, I obtains the same result.

This issue occurs with all `AltGR+...` combination.

Thanks

**Comment by zetamatta** [comment]
To support Linux, the package to read keyboard is replaced, but code is not enough to support AltGr.
I try to fix.

**Comment by zetamatta** [comment]
Would you tell me  for test ?

On French keyboard, by typing `AltGr` + `6` , `|` (pipeline mark) should be printed ?

**Comment by crile** [comment]
Yes, `AltGr` + `6` prints `|`

**Comment by zetamatta** [comment]
Thank you. I understand that  the prefix code `^[` (\x1B:ESCAPE CODE)  should not be inserted.

**Comment by zetamatta** [comment]
I tried to fix. Would you test any one of these versions ?

(amd64) 
https://ci.appveyor.com/project/zetamatta/nyagos/builds/22308933/job/868bkgva5duj1qmr/artifacts

OR  

(386)
https://ci.appveyor.com/project/zetamatta/nyagos/builds/22308933/job/0tw6lv1n995vjb6g/artifacts

**Comment by crile** [comment]
Thanks, it is fixed (Tested with amd64 build).
That a quick answer, thanks again.

**Comment by zetamatta** [comment]
Thank you for creating the issue and testing !

**Comment by zetamatta** [comment]
Fixed on [4.4.1_1](https://github.com/zetamatta/nyagos/releases/tag/4.4.1_1)
