### ISSUE TITLE
Incompatible cmd command invokation option

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#359]
nyagos -c like cmd /c
nyagos -k like cmd /k

But incompatible.

open test.txt
```shell
$ cmd /k notepad test.txt
```

do not open test.txt
```shell
$ nyagos -k notepad test.txt
```

---

nyagosの-k/-cですが、cmdと違いクォートしないと期待した動作になりません...が、これだとパス名などクォートが必要なパラメタ付きでの呼び出しに難があります
cmdと同様、可変長引数的に引き渡しできるようになると嬉しいです。

(vimのshell/shellcmdargをセットしましたが、動作的に利用が無理だな...となった次第です)

**Comment by tsuyoshicho** [comment]
追記

vimでいえば、shellquote/shellxquoteでのクォートやshellxescapeでのエスケープはあるので、まったくだめだとは思わないので、再度いろいろ試します。

ただ、cmdの^で記号エスケープとかそのあたりとの絡みも考える必要がありそうです。
合せる必要はないですが、個別パラメタにしたときどうするか? とか 逆に""でクォートするが、中の記号はどこまで平気で、中の"はどうすべきなのか? が不明なので...

**Comment by zetamatta** [comment]
cmd.exe の中から cmd.exe を呼び出す形でテストしてみたところ

```
$ cmd /c echoargs "1 \" 2"
[echoargs] [1 " 2]

$ cmd /c echoargs "1 ^" 2"
[echoargs] [1 ^] [2]

$ cmd /c echoargs "1 "" 2"
[echoargs] [1 "] [2]
```

となりましたので、二重引用符の中に二重引用符を入れるには `\"` でエスケープする必要がありそうです（echoargs は Go で作った  `fmt.Printf("[%s]\n", strings.Join(os.Args, "] [")) ` するだけの実行ファイルです）

同様な形になるよう修正してみました。

* (amd64バイナリ) https://ci.appveyor.com/project/zetamatta/nyagos/builds/23070441/job/f4djla7q04xya06c/artifacts
* (386バイナリ) https://ci.appveyor.com/project/zetamatta/nyagos/builds/23070441/job/9cp1uva8dm5txbfj/artifacts

**Comment by tsuyoshicho** [comment]
ちょっとためしてみます

**Comment by tsuyoshicho** [comment]
コマンドの引数としては問題なくエスケープできているのを確認しました。

ただ、...あれ

```
nyagos -c echo "a" > test.txt
```

として動きますね。

naygos -c xxx xxx xxx の形式 ("xxx xxx xxx"ではないの意)で大丈夫だったんですね、ちょっと自分のチェックも不正確だったようですみません。

**Comment by zetamatta** [comment]
すみません。一旦、当 issue はクローズさせていただきます。
具体的な要修正箇所がありましたら、お手数ですが、再オープンをお願いいたします。

**Comment by tsuyoshicho** [comment]
了解です。
