### ISSUE TITLE
Zero width char deletion problem?

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#360]
Example 👨‍👩
This emoji is 👨 and ZWJ (zero width joiner)  and 👩

Paste nyagos console and back space. then remain display dot char
But clear all chars(return to no error/no exec)

---

notepadへコピーして確認できると思いますが(notepadなら👨‍👩を張り付けると👨 (ZWJ) 👩になると思います)
この状態でのバックスペースでの絵文字の結合分解削除で、表示にゴミが残ります...
なんとなくですが、👨 や 👩が2文字幅で表示不能文字(計4つ)が出てて、そこで合計3文字削除するので1文字残る感じです。

削除する文字によってカーソル制御する+表示が2文字のとき、2文字分は後退させる必要はあるかもしれません。

もっともUnicodeでいくと幅がきまらないものとか可変とかあるので、そういう仕様、でもいい気もしますが...

**Comment by zetamatta** [comment]
( This problem is too difficut for me to write in English. )

文字の幅については頭が痛い問題で、自分もずっと認識していました。

mattn/go-runewidth でカーソルを戻す時に発行するバックスペースの個数を算出しています。ですが、Windows のコンソールでの実際の文字幅は Unicode の規格のものと微妙に違うので、文字によっては本件のような問題が発生します。

以前は文字が出力する度にカーソル位置を計測して文字幅を記録するような対応をしていたのですが、速度的に不利であるので、現在は無効にしています。（仮想マシン内ではコンソールがすごく遅くなる時があるので、速度を下げる要因を少しでも減らしたかったんですね。これをやると出力のバッファリングもやりにくくなるので）

また、Linux 対応に伴って、せっかく入力は mattn/go-tty 、出力は mattn/go-colorable と I/O を外出しているわけですので、あまり直接コンソールを触るのははばかられるというのもありました。
（まぁ、場合分けすればいいだけの話なのですが）

ということで、理想的な解決案不在のまま、文字幅問題はずっと先送りしているという状況です。Windowsのコンソールでの文字幅の決定ルールが明確に分かれば、問題は綺麗に片付くのですが…

すぐに解決する目処はないのですが、長期的な懸案でユーザのみなさんにも問題を共有しておきたいので、しばらく、この issue は Open 状態としておいてください。

**Comment by zetamatta** [comment]
ご報告いただいた件は、Windows コンソールと Unicode の規格の差とは更に別の、複数のコードポイントの組み合わせで別の文字に切り替えるという、最近 Unicode に現れた難しい問題ですね。
こちらもどうしましょうかね（頭をかかえる）

**Comment by zetamatta** [comment]
先に一旦コメントを書いたのですが、別の問題とゴッチャになっていたので、消しました。

**Comment by tsuyoshicho** [comment]
ちょっと説明がわかりにくいでね、書き直します。

1. notepadで確認できるが、絵文字には結合タイプがある
2. nyagosコンソールにこの結合文字をペーストし、バックスペース削除すると、ゴミがのこる
3. なんとなく2x2の不明文字の記号を3文字(絵文字2つと結合の0幅1)の分削除しているように見える

仕様でもいいのですが、0幅文字の削除で動きがあるのがやっぱり気になったので、という所です。
(フォントによっては正常表示される、でしょうか?)

そもそも表示対象外、でももちろん問題はないですが...

**Comment by zetamatta** [comment]
あ、問題については理解しているつもりです。
実のところ、結合タイプ以前のところで文字幅の管理がきちんと出来てなくて、そちらについて記していたのですが、よく考えるとそれとこれは別の話なので一旦消しちゃったという次第です。

一応問題としては理解しているつもりです。
（ところでコンソールのフォント、何がよいでしょうか？タイプすると認識はされますが、vim でも type でも文字が ?? となってしまうので…）

で、本題ですが、あまり「表示対象外」と切り捨てたくはなくて、できることはきちんと対応したいと考えています。

**Comment by tsuyoshicho** [comment]
ConEmu - cmd/nyagos - vimとnotepad、gVimとあって

* notepad Myricaですが代替フォント(Symbol?)で表示されますね
* ConEmuをMyricaにしてます
  * cmdはConEmuがMyricaで表示の場合代替表示されます、(notepadと同じ)、素だと無理
  * nyagosはご承知のとおり
  * CLI vimはコンソールのフォントに依存...ですが最新のvimでちょっと変なので別途調べます
* gVimだとDirextX系のレンダリングでカラーEmojiがOKになりました。(参考までの情報)

すみません、話に出してはいますが、あまりvim自体は気にしなくていいはずです...

**Comment by zetamatta** [comment]
すごく安直ですが、ゼロ幅接合子(U+200D)が入力された時、そのままではなく `<ZWJ>` と表示するようにしました。5文字で表示されますが、編集はひとかたまりで扱え、カーソル位置もおかしくならないと思います。

なお、Enter を押下すれば、本来の文字の方がコマンドに引き渡されます。扱いとしてはコントロール文字と同じです。


* (amd64バイナリ) 
https://ci.appveyor.com/project/zetamatta/nyagos/builds/23093265/job/emu0b93157jmmru0/artifacts
* (i386バイナリ)
https://ci.appveyor.com/project/zetamatta/nyagos/builds/23093265/job/v40ayvlnwj5gj7f1/artifacts

本当はゼロ幅接合子の意味にそった表示ができた方がいいと思いますが、連結される方の文字すら豆腐な状態で、あまり厳密さを追っても仕方がないかなと思い、誤動作チックなところだけ直しておくのが無難かなと思いました。

**Comment by tsuyoshicho** [comment]
のちほど見てみます

**Comment by zetamatta** [comment]
会社のWindows7 環境ではそれなりに動いていたんですが、自宅の Windows10 環境だと、だめだめですねぇ。👨と 👩 の方がなんかおかしいのか…

**Comment by zetamatta** [comment]
「👨‍👩」をクリップボードにペーストしたものをダンプしてみたところ

    <1F468>[2] <200D>[0] <1F469>[2]

（`<～>` は Unicode 番号、`[～]` は mattn/go-runewidth による文字幅数）
Windows7 のコマンドプロンプトは 👨と 👩が2桁相当になっていて期待どおりの挙動ですが、Windows10のコマンドプロンプトだと

![image](https://user-images.githubusercontent.com/3752189/54436157-58519c80-4775-11e9-9005-d162546a2711.png)

なんでや…

**Comment by tsuyoshicho** [comment]
確認しました。
たしかにWindows10でやると、同じになりますね。

当初のタイトル的な0幅文字、ひいては残存の文字がない状態にはなったので、前進はしているはずですが...

ちなみに、簡単なgoの出力とかで、

> <1F468>[2] <200D>[0] <1F469>[2]

を出力すると絵文字になるのか、上記のNG文字になるのか、どっちでしょうね...

**Comment by zetamatta** [comment]
クリップボードそのままの出力も足してみると、こんな感じですね

![image](https://user-images.githubusercontent.com/3752189/54437440-f6defd00-4777-11e9-8917-baf4eb857c91.png)

```go
// +build ignore

package main

import (
	"fmt"
	"os"

	"github.com/atotto/clipboard"
	"github.com/mattn/go-runewidth"
)

func main() {
	text, err := clipboard.ReadAll()
	if err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		return
	}
	for _, r := range text {
		fmt.Printf("<%X>[%d] ", r,runewidth.RuneWidth(r))
	}
	fmt.Println()
	fmt.Println(text)
}
```

**Comment by zetamatta** [comment]
ConEmu 経由だと一応期待通り…

![image](https://user-images.githubusercontent.com/3752189/54439416-18da7e80-477c-11e9-8a78-18b076970c6b.png)

**Comment by tsuyoshicho** [comment]
ああ、ConEmuだとたしかに...

**Comment by zetamatta** [comment]
どうも、サロゲートペアな Unicode （U+10000以上）がうまく出力できていない雰囲気です。

[UnicodeのEmojiの一覧 - Wikipedia](https://ja.wikipedia.org/wiki/Unicode%E3%81%AEEmoji%E3%81%AE%E4%B8%80%E8%A6%A7)を見ながらテストしてみましたが、U+3299 の「㊙」は表示できますが、U+1F004の「🀄」、絵文字ではない「𠮷」(U+20BB7) もアウトでした。

**Comment by zetamatta** [comment]
コマンドプロンプトではサロゲートペアな Unicode の出力は今のところサポートされていないようです（入力は出来るのに何故…）。よって：

* サロゲートペアな Unicode
* 文字幅がゼロの Unicode （ゼロ幅接合子を含む）

は双方とも `<NNNNN>` 形式で出力するように統一しました。
（例： 👨‍👩を Ctrl-Y でペーストすると `<1F468><200D><1F469>` になる）

ただ、将来的にサロゲートペアな Unicode の出力がサポートされる場合や、Linux のことも考慮して、`--output-surrogate-pair` という起動オプションを用意しました。これをセットすると、サロゲートペアな文字もそのまま出力します。

**Comment by tsuyoshicho** [comment]
ありがとうございます。

API的にいけるようになったらデフォルト切り替えですかね。

https://stackoverflow.com/questions/50179492/output-utf8-in-console-with-visual-studio-wide-stream

**Comment by zetamatta** [comment]
そうですね。API Ok なら、そちらへ自動切り替えしたいところです。

（現状、コンソールのバッファのひとマスが WCHAR (16bit) になっていて、そもそもサロゲートペアな Unicode が入らないようなので、おそらく Microsoft もすぐに対応するのが難しいんじゃないかと思います。が、emoji は需要もあるでしょうし、気長に待ちますか…）

**Comment by zetamatta** [comment]
一応、問題は解決したと思われますので、Close します。残件があるなら再オープンをお願いします。
