### ISSUE TITLE
マウスを使用せずに、クリップボードにあるディレクトリにchdirしたい

### ISSUE THREAD

**Issue by tostos5963** [zetamatta/nyagos#363]
マウスを使用せずに、クリップボードにあるディレクトリにchdirしたいです。

旧バージョンの nyacus では
cbpath.exe（自作コマンド：クリップボードにディレクトリがあればそれを、
ファイル名ならそのファイルがあるディレクトリ名を、それ以外なら"."を標準出力に出力）
を使って、_nya に、

cdc{
    set P="\`cbpath.exe\`"
    cd "$P"
}

を設定したら、
> cdc

で、chdir できています。

nyagos で同じことをやるために、いろいろ設定を試しましたが上手くいきません。

.nyagos に
nyagos.alias.cdc = "cd \`cbpath.exe\`"
を設定して、
$ cdc
を実行したら、

chdir \`cbpath.exe\`: The system cannot find the file specified.
exit status 1

となります。

alias にせずに、コマンドラインで直接実行したら動作します。
$ cd \`cbpath.exe\`

cd.go を（"-c" オプションで上記動作をするように）修正して
$ cd -c
としたら良さそうですが、設定（or Lua？）でできるのであれば設定で対応したいので
いいやり方があれば教えていただけないでしょうか。

**Comment by zetamatta** [comment]
すみません。nyagos では逆クォート機能自体が Lua で実装されているために、エイリアスの中で動作していないようです。

設定だけで対応するならば、やはり Lua になりますが次のようなエイリアス関数を `.nyagos` に定義すればよいかと思います。

```lua
nyagos.alias.cdc = function()
    nyagos.chdir(nyagos.eval("cbpath"))
end
```

いかがでしょうか？

**Comment by tostos5963** [comment]
早い回答ありがとうございます。
動作しました。
これで、nyacusから移行できそうです。

**Comment by sambatriste** [comment]
横からすみません。

私も似たようなことがしたくて困っていましたが、このissueをみて解決しました。

これをエイリアスにしたかったので、
```sh
cd `ghq list -p | peco`
```

このissueを見て
```lua
nyagos.alias.gcd = function()
  nyagos.chdir(nyagos.eval("ghq list -p | peco"))
end
```
のようにして、期待通りの結果を得ることができました。

ありがとうございました。

**Comment by zetamatta** [comment]
@tostos5963 & @sambatriste 
情報ありがとうございました。
エイリアス文字列の中で逆クォートを使いたいというニーズは見逃していました。
今回の件については Lua 関数で代替可能ですが、同じようなことをしたい人は他にもいらっしゃりそうなので、できるようにできないか検討したいと思います。

**Comment by zetamatta** [comment]
```lua
nyagos.alias.cdc = "cd `cbpath.exe`"
```

でも期待どおり動作するようにしました。正式バイナリは次のバージョンより反映ですが、スナップショットは下記よりダウンロード可能です。

* amd64 https://ci.appveyor.com/project/zetamatta/nyagos/builds/23458680/job/rjknulpbjb0gvxp8/artifacts
* i386 https://ci.appveyor.com/project/zetamatta/nyagos/builds/23458680/job/vrxcp4k8s4o9rl2q/artifacts

よろしければ、ご確認ください。

**Comment by tostos5963** [comment]
対応ありがとうございます。早いですね。
期待通り動作することを確認しました。

**Comment by zetamatta** [comment]
ご確認ありがとうございます。
では、本件、一旦、クローズさせていただきます。
