### ISSUE TITLE
box.lua : history cd でのboxの移動がおかしい

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#364]
rel #354

```
$ d:
$ cd repo
<ctrl-x> -> h
```

としたとき

```
D:\repo D:\            
D:\repo D:\            
D:\repo D:\            
D:\repo D:\            
D:\repo D:\            
D:\repo D:\            
D:\repo D:\            
```                       

のように、要素選択で表示が上にずりあがり、画面を埋めてしまうようです。

```
$ ls | box
```

は問題なく(1行に複数要素)、履歴のコマンド/git revも大丈夫(長いため1行1要素だから?)でした。

> Nihongo Yet Another GOing Shell 4.4.2_0-windows-amd64 by go1.12
> (c) 2014-2019 NYAOS.ORG <http://www.nyaos.org>

**Comment by zetamatta** [comment]
ありがとうございます

**foo.cmd**
```
@echo off
echo hogehoge
echo uahaha
```

`foo.cmd | box` でも再現できますね

**Comment by zetamatta** [comment]
原因がわかりました。`\x1B[0A` というエスケープシーケンスがありますが、エミュレーション（[go-colorable](https://github.com/mattn/go-colorable)ライブラリ）だと期待通り何もしない（０個カーソルを上に移動）のですが、Windows10 のネイティブコンソールだと１個上に上がってしまいます。

nyagos は Windows10 だと、ネイティブコンソールをそのまま使うので、それで問題が表面化したようです。

**Comment by zetamatta** [comment]
すみません。コミットログに Fix と書いてしまって、自動クローズされてしまいました。

**Comment by zetamatta** [comment]
Linux 版でも再現しました。

カーソルを上に移動させる必要がないにも関わらず `ESC[0A` というエスケープシーケンスを発行している不具合がありましたので、修正しました。下記、修正バイナリです。

* [386 binary](https://ci.appveyor.com/project/zetamatta/nyagos/builds/23818918/job/xg1pg4o2au9h28j6/artifacts)
* [amd64 binary](https://ci.appveyor.com/project/zetamatta/nyagos/builds/23818918/job/xg1pg4o2au9h28j6/artifacts)

**Comment by tsuyoshicho** [comment]
対応ありがとうございます。
確認してみます。

**Comment by zetamatta** [comment]
（うっかり develop ブランチの方を更新していましたので、master へも適用しました。
　develop でも問題はないはずですが、一応、念の為）

**Comment by tsuyoshicho** [comment]
確認しました。
問題動作は解決し、変になることはないですね。

\# Win10の挙動変更はLinuxなどのエスケープシーケンスへの追従というか動作をそろえようと拡充した結果かもしれませんね。

**Comment by zetamatta** [comment]
ご確認ありがとうございます。致命的な不具合ではありませんが、master が未解決の不具合を抱えているのは気持ちわるいので、なるべく早めにバイナリをリリースいたします。

>  Win10の挙動変更はLinuxなどのエスケープシーケンスへの追従というか動作をそろえようと拡充した結果かもしれませんね

あ、これはですね。以前は「常に go-colorable でのエミュレーションを実行させていた」のを「Windows10ならばエミュレーションせず、エスケープシーケンスをそのまま標準出力に出す」ようにわざわざ修正していたので、たぶん nyagos 側がトリガーだと思います。

言ってみれば「要らんことするな」案件ではあるんですが

* なるべく標準品を使うべき
* どこの端末でも動くよう、出力をあらかじめ「より汎用化」しておくべき
    * そういう意味では今回 `ESC[0A` をあぶり出せたのはねらいどおり
* Windows7 のサポート期限が切れたら go-colorable を切ってバイナリを軽くしたいが、やるなら早めにやって問題点を早々に洗い出しておきたい

など<S>と供述</S>思うところありまして…お騒がせしました。

**Comment by zetamatta** [comment]
本修正を反映したバイナリ 4.4.2_2 をリリースしました。
[Release 4.4.2_2 · zetamatta/nyagos](https://github.com/zetamatta/nyagos/releases/tag/4.4.2_2)

**Comment by tsuyoshicho** [comment]
ありがとうございます。
環境をアップデートしました。
