### ISSUE TITLE
.nyagosでsuffixが設定できない

### ISSUE THREAD

**Issue by maskedw** [zetamatta/nyagos#367]
NYAGOSバージョン 
`Nihongo Yet Another GOing Shell 4.4.3_0-windows-amd64 by go1.12.4`

いつも便利に使わせてもらっています。

https://github.com/zetamatta/nyagos/blob/master/Doc/07-LuaFunctions_ja.md#nyagosargsfilter

上記の例を参考に、suffixを設定したい(具体的には拡張子.pyの時にpy.exeを呼び出したい)のですが、`${HOME}/.nyagos`で設定をしようとしてもエラーになってしまいます。

```
C:\home\.nyagos:1: attempt to call a non-function object
stack traceback:
        C:\home\.nyagos:1: in main chunk
        [G]: ?
```

ドキュメントに記載のある2種類の記法

```
コマンド
    suffix 拡張子 インタプリタ名 引数1 引数2 …
Lua:関数
    suffix("拡張子",{"インタプリタ名","引数1"…})
```

のどちらも試しましたが、同じエラーになりました。

```
suffix "py" "py.exe"
suffix("py", {"py.exe"})
```

https://qiita.com/spiegel-im-spiegel/items/dac2f4c1dc2ec9bb5e7d

上記の例では、`suffix.py="py"`という記法も記載されていたので試しましたが、やはりエラーになってしまいます。

```
C:\home\.nyagos:1: attempt to index a non-table object(nil)
stack traceback:
        C:\home\.nyagos:1: in main chunk
        [G]: ?
```

suffixはどこにどうやって設定すればよいのでしょうか？

**Comment by zetamatta** [comment]
コマンドラインで直接 `suffix` だけをタイプしていただくとどうなりますでしょうか？

```
$ suffix
'suffix' is not recognized as an internal or external command,
operable program or batch file
```

などが出ていたら、`suffix` コマンドを定義したスクリプト（`nyagos.d\suffix.lua` ）が読み込まれていない可能性があります。もし、そうであれば、`nyagos.d/` 以下のツリーを `nyagos.exe` と並列の位置のフォルダーの下においていただく必要があります。

もし、`suffix` だけタイプしてエラーにならないようであれば、`.nyagos` の1行目を見せていただけますでしょうか。`.nyagos` は Lua の文法で記載するので、理論上は `suffix("py", {"py.exe"})` でも `suffix.py="py"` でもよいはずなのですが…

以上、よろしくお願いたします。

**Comment by maskedw** [comment]
直接`suffix`コマンドを実行した結果は下記の通りでした。
```
$ suffix
'suffix' is not recognized as an internal or external command,
operable program or batch file
exit status 255
```

`mklink`で`nyagos.exe`のシンボリックをPATHを通したディレクトリに作成して実行していたのですが、
それがまずかったみたいです。`nyagos.exe`の実体を直接実行すると`suffix`コマンドが正常に機能しました。

この仕様を把握できていませんでした。
> などが出ていたら、suffix コマンドを定義したスクリプト（nyagos.d\suffix.lua ）が読み込まれていない可能性があります。もし、そうであれば、nyagos.d/ 以下のツリーを nyagos.exe と並列の位置のフォルダーの下においていただく必要があります。

`.exe`をシンボリックリンクする運用はやめるようにします。ありがとうございました。

**Comment by zetamatta** [comment]
情報ありがとうございます。
なるほど、nyagos.exe 自身がシンボリックリンクだった時に、相対パスがずれる可能性について考慮が足りませんでした。可能なら何か対策を考えてみます。
