### ISSUE TITLE
.nyagosでio.closeがnil

### ISSUE THREAD

**Issue by maskedw** [zetamatta/nyagos#368]
NYAGOSバージョン
Nihongo Yet Another GOing Shell 4.4.3_0-windows-amd64 by go1.12.4

https://qiita.com/JugernautOnishi/items/bbfd18c3776c012b4060

上記で紹介されているスクリプトを実行するとエラーになってしまうので調べていると、
`io.close()`を呼び出している部分でエラーになっていました。

```
print(type(io.close))
<< nil
```

[4.3.2のリリースノート](https://github.com/zetamatta/nyagos/releases/tag/4.3.2_0)の下記の変更の影響でしょうか？

>  io.* を NYAGOS の自前バージョンに置き変えた

代替え方法はありますか？

**Comment by zetamatta** [comment]
すみません。移植漏れです（メソッドではない `io.close` があるとは思いませんでした…）

とりあえず、`io.close(f)` の代わりに、`f:close()` を使ってください。

**Comment by zetamatta** [comment]
[(#368) Fix io.close did not exist. · zetamatta/nyagos@7aa7fdd](https://github.com/zetamatta/nyagos/commit/7aa7fdddd7f65881af323fa268e34afae2c79791)にて、io.close 実装しました。

**Comment by zetamatta** [comment]
修正を反映したバイナリ 4.4.4_0 を公開しました。
https://github.com/zetamatta/nyagos/releases/tag/4.4.4_0
