### ISSUE TITLE
io.openのr+がサポートされていない？

### ISSUE THREAD

**Issue by maskedw** [zetamatta/nyagos#369]
NYAGOSバージョン
Nihongo Yet Another GOing Shell 4.4.3_0-windows-amd64 by go1.12.4

以下のように`r+`でopenを試みると、存在するパスであっても常に`nil`が返ってきます。
```lua
local fp = io.open(path, 'r+')
```

[io.open() with w+ mode #332](https://github.com/zetamatta/nyagos/issues/332)
w+がまだ未実装であるissueがありましたが、r+も未実装でしょうか？

**Comment by zetamatta** [comment]
はい。まだです。

**Comment by maskedw** [comment]
了解です。こういう未実装系のissueはcloseした方がよいですか？

**Comment by zetamatta** [comment]
あ、とりあえず、おいといてください（自分向けプレッシャー用に）。
実装したら close します。

**Comment by zetamatta** [comment]
[(#369) & (#332): Rewrite iolib for Lua & implement r+ and w+ modes · zetamatta/nyagos@f2fc1f0](https://github.com/zetamatta/nyagos/commit/f2fc1f0bfce2f3824a4a214d7df78ce3dc581d75) にて、r+ モードを実装しました。

**Comment by zetamatta** [comment]
修正を反映したバイナリ 4.4.4_0 を公開しました。
https://github.com/zetamatta/nyagos/releases/tag/4.4.4_0
