### ISSUE TITLE
組み込みのpwdコマンドがUNCパス上で正しく動作しない

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#37]
UNCパス上で`pwd`コマンドを実行しても**ホスト名**と**共有名**を返しません。

例えば
```
\\foo\bar\hoge\fuga
```
で`pwd`を実行した場合、実行結果は
```
hoge\fuga
```
となります。
commands/pwd.go内の`dos.Getwd`に原因があるようで`os.Getwd`だと大丈夫です。

**Comment by zetamatta** [comment]
dos.Getwd はカレントディレクトリの英大文字・小文字を正しく修正するコードがあるのですが、UNCパスのホスト名で、ディレクトリ一覧を取れなくなってエラー扱いされてしまっていたようです。

エラーになったら、そこで大文字・小文字の修正をストップして、エラー自体は無視し、その時点のものをそのまま使用するようにしました。バイナリは、Lua 5.3 対応あたりが出来ましたらアップします。

**Comment by nocd5** [comment]
ありがとうございます。 c3d5c756a107b1af517ab945e0300e4dfabc2c2d で修正されていること確認いたしました。
こちらのissue閉じさせて頂きます
