### ISSUE TITLE
Question:  Add .lua to pathext automaticaly?

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#370]
(問題の本質は自分の環境にあるので、そこは一旦置いておいてください)

以下のような問題が起き、調査した結果による質問です。

## 問題と経緯

nyagos上からvimでnyagosリポジトリのluaファイルを編集しようとすると、vim起動後標準の関連付けがされたメモ帳で開こうとする動作になった(閉じると何度でも開くため、vimの操作ができなくなる)

vim -u NONEすると発生しないことから、自分の環境問題があることがわかったが、合せて調べたとき、エクスプローラやコマンドプロンプトでは問題がなかった。

また、nyagosからcmdを内部で開き、そこから実行しても発生した。

環境変数差分を見たところ、以下のような差分があった

### 正常

```text
original
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.RB;.RBW

cmd only
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.RB;.RBW
```

### 問題あるとき

```text
nyagos
nyagos cmd start
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.RB;.RBW;.awk;.js;.lua;.pl;.ps1;.rb;.vbs;.wsf;.py
```

そして、nyagos上で.luaのないオリジナル設定を再設定してから実施したところ、問題は発生しなかった。
また、コマンドプロンプトに.luaがある設定をしたところ問題が発生した

また関連確認としてバッチファイル(.bat)はこういった問題は出ていない

## 質問
.luaなどが追加されているのが見えるが、これはnyagosで設定しているものか? (lua実行環境はあるが、上記にあるようにpathextには設定はない)

そのとき
1. 設定の理由はどのようなものか
2. 抑制方法があるならばおしえていただきたい (*.lua内でしているか見てみたが、そちらにはなかった)

よろしくおねがいします。

**Comment by tsuyoshicho** [comment]
あらためて見たら、`nyagos/nyagos.d/suffix.lua` PATHEXTを拡張する機能を提供している?

**Comment by zetamatta** [comment]
suffix コマンドで定義された拡張子に対して、PATHEXT を登録するようになっているようです。

経緯はうろ覚えですが、PATHEXT に登録された拡張子でないと、PATH上から実行可能ファイルを探せないことになっているからだったと思います。これは無論 CMD.EXE のルールであって、nyagos が従う理由はなく、おれおれPATHEXT変数なんかを用意すればよい話でした。
ですが、nyagos はもう仕様があまりにも多すぎる状況になっており、新たな新仕様を設けるのではなく、なるべく既存の仕様にのっかった形の方が望ましいと考えたのだと思います。

さて、`.awk` `.js` `.lua` `.pl` `.ps1` `.rb` `.vbs` `.wsf` `.py` が追加されているのは、おそらく（ドットではなく、アンダスコアで始まる名前の方の） `_nyagos` に記載された

```
suffix >nul 2>nul
if not errorlevel 1 then
    suffix "awk=gawk -f"
    suffix "js=cscript //nologo"
    suffix "lua=nyagos.exe --norc --lua-file"
    suffix "pl=perl"
    suffix "ps1=powershell -ExecutionPolicy RemoteSigned -file"
    suffix "rb=ruby"
    suffix "vbs=cscript //nologo"
    suffix "wsf=cscript //nologo"
    suffix "py=python"
end
```

がトリガーだと思います。ここの suffix が nyagos.d/suffix.lua の suffix関数を呼んでおり、そこで PATHEXT が追加されているのではないかと思います。なので、このあたりの suffix 文を削除してやれば、PATHEXT への追加は抑制されるはずです。

PATHEXT に追加する仕様については、あくまで仕様を少なめにする意図でそうしただけであって、それでかえって環境が混乱するような状況になるのでしたら、PATHEXT をいじらない方向へ修正するのもやぶさかではありません。

**Comment by tsuyoshicho** [comment]
ありがとうございます。

仕様については、根本原因が判明しないとなんとも言えませんが、基本は問題ないと思います。
ただ逆になにかしらの問題を突いてしまっていたら、その旨再度Issueにして報告しますね。

とりあえず、上記をどうにかしておきます...
