### ISSUE TITLE
ファイル名に.を含む実行ファイルを参照できない

### ISSUE THREAD

**Issue by terepanda** [zetamatta/nyagos#371]
こんにちは

パスの通っている場所にある実行ファイルを呼び出そうとしたとき、ファイル名に「.」(ドット)が含まれていると、フルパスを指定しないとnyagosで認識できない現象が発生しています。
nyagosの問題なのかはわからないのですが、試しにpowershellで該当ファイルを実行してみるとファイル名だけで実行できました。

使用しているバージョンは
Nihongo Yet Another GOing Shell 4.4.4_2-windows-amd64 by go1.12.5
です。

Goのバージョン1.12をインストーラでインストールした後に、追加で go1.11.1 をインストールしようとして下記のページの手順を実行している時に気付きました。
https://golang.org/doc/install#extra_versions
```
$ go get golang.org/dl/go1.11.1
$ go1.11.1 download
'go1.11.1' is not recognized as an internal or external command,
operable program or batch file
exit status 255
```

環境変数のPathに設定されているディレクトリにある実行ファイルでも、ファイル名に「.」が含まれていると参照できないみたいです。
```
$ which go1.11.1
which go1.11.1: not found
exit status 1
$ where go1.11.1
C:\Users\<username>\.go\bin\go1.11.1.exe
```
(.が含まれていなければ問題なし)
```
$ which gobin
C:\Users\<username>\.go\bin\gobin.exe
```

```
$ which pip3.6
which pip3.6: not found
exit status 1
$ where pip3.6
C:\Python\Python36-32\Scripts\pip3.6.exe
$ which pip3
C:\Python\Python36-32\Scripts\pip3.exe
```

(Powershell)
```
PS C:\work> go1.11.1 version
go version go1.11.1 windows/amd64
PS C:\work> pip3.6 -V
pip 19.0.3 from c:\python\python36-32\lib\site-packages\pip (python 3.6)
```

環境
Nihongo Yet Another GOing Shell 4.4.4_2-windows-amd64 by go1.12.5
Windows10 Home 1809

お手数ですが、お時間ある時にご確認いただけますか？
よろしくお願いします。

**Comment by zetamatta** [comment]
ありがとうございます。
hoge.muta.cmd というバッチファイルでも

* CMD.EXE では hoge.muta でも hoge.muta.cmd でも実行できる
* nyagos.exe では hoge.muta では実行できない

と確認しました。おそらく、ドットが含まれていると、拡張子が省略されていないと判断しているためだと思います。近日中に修正したいと思います。

**Comment by zetamatta** [comment]
foo.bar.cmd 等を foo.bar と呼び出せるよう修正しました。本修正は次のリリースに反映予定ですが、最新のスナップショットのバイナリには既に反映されていますので、よろしければご確認ください。

* [nyagos 1.0.1322 - AppVeyor/amd64](https://ci.appveyor.com/project/zetamatta/nyagos/builds/25638174/job/c6cgpgq8d1q94ogl/artifacts)
* [nyagos 1.0.1322 - AppVeyor/386](https://ci.appveyor.com/project/zetamatta/nyagos/builds/25638174/job/wxui7oqq6cyj2jo2/artifacts)

以上、よろしくお願いいたします。

**Comment by terepanda** [comment]
ありがとうございます😄
nyagos-amd64-1.0.1322 でファイル名にドットが含まれる実行ファイルを呼び出せるようになりました。
```
$ go1.11.1 version
go version go1.11.1 windows/amd64
$ pip3.6 -V
pip 19.0.3 from c:\python\python36-32\lib\site-packages\pip (python 3.6)
```
