### ISSUE TITLE
Autocompletion mechanism

### ISSUE THREAD

**Issue by malys** [zetamatta/nyagos#376]
Hi,
Is it possible to use bash or zsh autocompletion mechanism with nyagos?

Great job for this application.
Thx,
Malys

**Comment by zetamatta** [comment]
Thank you for using nyagos.

Now, if the **autocompletion** means `completion without pressing tab-key`, I have to answer *No*.
Nyagos has only completions that requires pressing the TAB key.

Or, if **autocompletion** means `customizing completion for commands`, I can tell you some mechanism exist.

* [nyagos.complete_for["COMMAND"] = function(args) ... end](https://github.com/zetamatta/nyagos/blob/master/Doc/07-LuaFunctions_en.md#nyagoscomplete_forcommand--functionargs--end)
    * example (1) [go sub-command completion for nyagos ](https://gist.github.com/zetamatta/d86d0678806da1b86c7bf83f116ca5f6)
    * example (2) [git sub-command completion for NYAGOS](https://gist.github.com/zetamatta/a6a133e391916db55b38b1eb4f626bd9)
* [nyagos.completion_hook = function(c) ... end](https://github.com/zetamatta/nyagos/blob/master/Doc/07-LuaFunctions_en.md#nyagoscompletion_hook--functionc--end)
    * This older hook is called on tab-pressed for any-commands.

**Comment by malys** [comment]
Many CLi provides arguments to generate completion file compatible with bash 
ex: kubectl completion bash (see https://blog.heptio.com/kubectl-shell-autocomplete-heptioprotip-48dd023e0bf3)
Nyagos is it compatible with bash autocompletion format to use autocompletion bash ecosystem?
I would not be necessary to generate file like git4nyagos.lua.

**Comment by zetamatta** [comment]
No. Nyagos has no compatibility with bash's any format.
If there are needs , bash should be used.

**Comment by malys** [comment]
Thx
