### ISSUE TITLE
Feature Issue: subcommand ignore extension?

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#378]
[4.4.5_3](https://github.com/zetamatta/nyagos/releases/tag/4.4.5_3)のリリースで

> サブコマンド補完(complete_for)では拡張子は無視してコマンドのマッチングを行うようにした

とあり、ローカルで `nyagos.d/catalog/git.lua`, `nyagos.d/catalog/subcomplete.lua` の修正を試みたのですが

例えば、以下でexe版を除去すると、`git.exe` などでサブコマンドの補完が働かないように見えました。

https://github.com/tsuyoshicho/nyagos/blob/ad72bc4bc90ef5a44b6efe0eec5ebec3f482cd13/nyagos.d/catalog/subcomplete.lua#L46-L50

こちらのミスの可能性もありますが...

**Comment by zetamatta** [comment]
申し訳ありません。説明不足でした。補完用のフックには：

1. 昔からある `nyagos.complete_hook`
    * 何でもできるが、その分 Lua でガッツリ書かないといけない
    * nyagos.d/ にスクリプトがあるのは、こっち向け
2. 最近、試験的に追加した `nyagos.complete_for`
    * コマンドごとに特化していて、Luaコード少なめでよいが、そのかわり自由度が少ない
    * （bash の complete 文程度にコマンド特化の補完コードを楽に書けないかという試作品）

がありまして、後者の方を指していました。
なので、nyagos.d/ 以下にあるスクリプトにすぐ対応が必要なものではありません。
（というか、complete_hook 版の方の対応を忘れていたというべきかも）

**Comment by tsuyoshicho** [comment]
あー、なるほど了解です。

課題として残すか閉じるかはお任せします。

**Comment by zetamatta** [comment]
やや、やっつけで恐縮ですが、subcomplete.lua を修正して、コマンド名の拡張子を無視して、英大文字・小文字の区別をしないでコマンド名を照合するよう修正しました。これで個別のコマンド処理ごとに .exe つきのコマンド名を登録する必要はなくなります。
（ユーザからは全く変化が見えませんし、今後、コマンドを追加する時にひと手間減る程度の差しかありませんが…）

**Comment by tsuyoshicho** [comment]
ありがとうございます。

案外 .cmdや .batなどもあるので(npmやらのショートカットなど)有効なことは多いのではないかと思います。

**Comment by tsuyoshicho** [comment]
動作を見てみようと思いますが、すでに確認できているならクローズでよいかと思います

**Comment by zetamatta** [comment]
[4.4.5_4バイナリのリリース](https://github.com/zetamatta/nyagos/releases/tag/4.4.5_4)もしたので、一旦クローズします。何か問題見つかりましたら、再オープンいただければと存じます。
