### ISSUE TITLE
Feature request: command exec preexec/precmd(like postexec) hook

### ISSUE THREAD

**Issue by tsuyoshicho** [zetamatta/nyagos#379]
like https://github.com/rcaloras/bash-preexec

現在、[starship/starship](https://github.com/starship/starship) を使うことでプロンプトを改善しています。

code

```lua
-- prompt
nyagos.prompt = function(this)
  -- path,title,prompt
  local path = getCompressedPath(3):gsub('\\', '/')
  local title = path .. " - NYAGOS"
  local admin = nyagos.elevated()
  if admin then
    title = title .. "(admin)"
  end

  local prompt = ''
  if nyagos.which("starship") then
    prompt = prompt .. nyagos.eval('starship prompt 2> nul') ..  '$e[37;1m' .. ' '
  else
    local pathBlock = ''
    if admin then
      pathBlock = '$e[30;40;1m[$e[40;31;1m'..path..'$e[30;40;1m]$e[37;1m'
    else
      pathBlock = '$e[30;40;1m[$e[40;36;1m'..path..'$e[30;40;1m]$e[37;1m'
    end
    prompt = prompt .. makePrompt(pathBlock)
  end

  return nyagos.default_prompt(prompt,title)
end
```

(不明な関数などはおいといてください...)

[![Image from Gyazo](https://i.gyazo.com/06d9ca8b55660f24cb234f462e70910d.png)](https://gyazo.com/06d9ca8b55660f24cb234f462e70910d)

ただし、いくつかの機能が使えません。
その内の1つである、「コマンド実行から次のプロンプト復帰までの時間の表示([cmd_duration](https://starship.rs/config/#command-duration))」は、コンソールの処理実行前(preexec)に時間を記録し、再プロンプト表示時(bashはその前処理 precmd)の時間との差で表示を行っています。

独自ログ系とか、機能としては汎用なので、機能追加について検討していただけたら、と思います。

**Comment by zetamatta** [comment]
Ok です。要件を満たす道具立てを考えます

**Comment by tsuyoshicho** [comment]
note:
参考までに現在のstarshipが吐く、bash用のスクリプトです

https://gist.github.com/tsuyoshicho/d7f84c8add154c51247387d57cee4de5

**Comment by zetamatta** [comment]
@tsuyoshicho 

プロトタイプを [issue379 ブランチ](https://github.com/zetamatta/nyagos/tree/issue379)で作成中です。現在の仕様は下記のような感じです。よろしければコメントください。
（Done の args[0] がフルパスに変わってしまっているところは期待していない動作なので、要修正だと認識しています）

* [Prototype for amd64](https://ci.appveyor.com/project/zetamatta/nyagos/builds/32595100/job/l51njl8p7538swfp/artifacts)
* [Prototype for 386](https://ci.appveyor.com/project/zetamatta/nyagos/builds/32595100/job/u8rgsbpet54q9qok/artifacts)

To register:

```
nyagos.preexechook = function(args)
    io.write("Call ")
    for i=1,#args do
        io.write("[" .. args[i] .. "]")
    end
    io.write("\n")
end

nyagos.postexechook = function(args)
    io.write("Done ")
    for i=1,#args do
        io.write("[" .. args[i] .. "]")
    end
    io.write("\n")
end
```

To unregister:

```
nyagos.preexechook = nil
nyagos.postexechook = nil
```

Output of the test run:

```
<DESKTOP-LGGUCRA:~/go/src/github.com/zetamatta/nyagos>
$ ls | head -1
Call [head][-1]
Call [ls]
Done [ls]
Cmd/
Done [C:\Users\hymko\Share\bin\head.exe][-1]
<DESKTOP-LGGUCRA:~/go/src/github.com/zetamatta/nyagos>
$ 
```

**Comment by zetamatta** [comment]
postexechook 側で、preexechook と違って args[0] がフルパス化されてしまう問題の修正版です。

* [prototype for amd64](https://ci.appveyor.com/project/zetamatta/nyagos/builds/32596018/job/5bao67u8qp2idw0y/artifacts)
* [prototype for 386](https://ci.appveyor.com/project/zetamatta/nyagos/builds/32596018/job/0ikxovxrksc8w179/artifacts)

```
<DESKTOP-LGGUCRA:~/go/src/github.com/zetamatta/nyagos>
$ ls | head -1
Call Call [head][ls]
[-1]
Done [ls]
Cmd/
Done [head][-1]
<DESKTOP-LGGUCRA:~/go/src/github.com/zetamatta/nyagos>
$                                                            
```

`Call` が重なっているのはパイプラインの前後のコマンドが同時に動作するので仕方がないと考えています。

2,3日、手元で試験運用して、特に大きな問題がなければ master に組み込みたいと思います。機能的に追加リクエストなどあれば、意見・コメントください。

**Comment by tsuyoshicho** [comment]
試しますー。

**Comment by tsuyoshicho** [comment]
```lua
-- test pre/post hook
nyagos.env["STARSHIP_DURATION"] = '0'

nyagos.preexechook = function(args)
  nyagos.env["STARSHIP_START_TIME"] = tostring(os.time())
  -- io.write("start ")
  -- io.write(nyagos.env["STARSHIP_START_TIME"])
  -- io.write("\n")
end

nyagos.postexechook = function(args)
  nyagos.env["STARSHIP_END_TIME"] = tostring(os.time())
  nyagos.env["STARSHIP_DURATION"] = tostring(1000 * (tonumber(nyagos.env["STARSHIP_END_TIME"]) - tonumber(nyagos.env["STARSHIP_START_TIME"])))
  -- io.write("end ")
  -- io.write(nyagos.env["STARSHIP_END_TIME"])
  -- io.write(" duration ")
  -- io.write(nyagos.env["STARSHIP_DURATION"])
  -- io.write("\n")
end

-- prompt
nyagos.prompt = function(this)
  -- path,title,prompt
  local path = getCompressedPath(3):gsub('\\', '/')
  local title = path .. " - NYAGOS"
  local admin = nyagos.elevated()
  if admin then
    title = title .. "(admin)"
  end

  local prompt = ''
  if nyagos.which("starship") then
    duration = tonumber(nyagos.env["STARSHIP_DURATION"])
    if duration > 0 then
      prompt = prompt .. nyagos.eval('starship prompt --status=' ..  nyagos.env["ERRORLEVEL"] .. ' --cmd-duration=' .. nyagos.env["STARSHIP_DURATION"] .. ' 2> nul') ..  '$e[37;1m' .. ' '
    else
      prompt = prompt .. nyagos.eval('starship prompt --status=' ..  nyagos.env["ERRORLEVEL"] .. ' 2> nul') ..  '$e[37;1m' .. ' '
    end
  else
    local pathBlock = ''
    if admin then
      pathBlock = '$e[30;40;1m[$e[40;31;1m'..path..'$e[30;40;1m]$e[37;1m'
    else
      pathBlock = '$e[30;40;1m[$e[40;36;1m'..path..'$e[30;40;1m]$e[37;1m'
    end
    prompt = prompt .. makePrompt(pathBlock)
  end

  return nyagos.default_prompt(prompt,title)
end
```

として


[![Image from Gyazo](https://i.gyazo.com/7d4d3f9d9e74c1a4abe574dca3c042c4.png)](https://gyazo.com/7d4d3f9d9e74c1a4abe574dca3c042c4)

と期待した動作が取れました。

しいていえば、promptやpre/posthook内でevalしたら、それでもpre/posthookが動くので、とくにhook内でhookが動くとループしてエラーっぽいのが注意点というところでしょうか?

**Comment by zetamatta** [comment]
ご確認ありがとうございます。

無限呼び出し防止のために、フック呼び出し前後で context.Context の中に `type ExecHookFlagT struct{}` のインスタンスをキーに放り込んで、それが既に入っていたらフックは無視させていたんですが、exec や eval を呼ぶ時に Context が断絶してしまっていたみたいですね。

これはこれで問題なので、ちょっと対応を検討します
（が、今までやってなかったということは、何か障害があったような気がします…）

**Comment by tsuyoshicho** [comment]
機能リクエスト的なことについては自分は特にはないんです。

ただ、サンプルというか「直前に実行したコマンドをプロンプトに出す」みたいなのを.nyagos的にデフォルト記載とか例を記載してもいいかもしれないな、とは思いました。

そこらへんはお任せで...w

**Comment by zetamatta** [comment]
もうちょっと時間を置いてから master へマージするつもりだったのですが、別件 #383 での修正がはいり、ブランチがややこしくなるので、現時点での状態でマージしたいと思います。

**Comment by tsuyoshicho** [comment]
わかりました、ありがとうございます。

バグにおきをつけて...

**Comment by zetamatta** [comment]
バイナリ版反映（4.4.6_0 リリース）に伴い、本件、クローズいたします。
