### ISSUE TITLE
nyagos.gethistory()の引数にヒストリ数を超える値を与えると落ちる

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#38]
例えばヒストリ数が2000の場合に
```
lua_e "nyagos.gethistory(2002)"
```
とすると落ちます(2001でないのは、上記コマンドが実行時にヒストリに追加され、リスト長が2001になるため)。

リスト範囲外の参照なのですが、
落ちるのは期待動作ではないと思ったので報告させていただきます。

**Comment by zetamatta** [comment]
ご報告ありがとうございます。クラッシュする件はとりいそぎ修正いたしました。
NYAGOS の一行入力を、他のアプリケーションで使えるように諸々修正した際にエンバグしてしまったようです。
他にも何か怪しい挙動がありましたら、お知らせください。（特にヒストリ関連）

**Comment by nocd5** [comment]
ありがとうございます。 0c14d46d89a976f5c4743db0a3dab36a39ffa75a で件の問題が修正されていること確認いたしました。

こちらcloseさせていただきます。
何かありましたら、また報告させていただきます。
