### ISSUE TITLE
ヒストリが保存されない

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#39]
メモリ上のヒストリにはappendされているのですが、
`~/AppData/Roaming/NYAOS_ORG/nyagos.history`が更新されません。

思ったのですが
https://github.com/zetamatta/nyagos/blob/0c14d46d89a976f5c4743db0a3dab36a39ffa75a/src/nyagos.go#L137
この条件って真になることありますかね？

**Comment by zetamatta** [comment]
すみません！条件の左辺と右辺が逆でした。
ヒストリが増えた時だけ更新のはずだったのですが…
ご報告ありがとうございます。

**Comment by nocd5** [comment]
なるほど、そういうことでしたか！
775244fc218f7616f2e885d8e22f255f7f85fbf7 でヒストリが保存されるようになりました。
修正ありがとうございます。
