### ISSUE TITLE
ウィンドウアクティブ後の最初のキーが２つ入力されます

### ISSUE THREAD

**Issue by tostos5963** [zetamatta/nyagos#393]
【操作】
(1) nyagos.exe を実行
(2) ALT+TAB で別ウィンドウ（エクスプローラ）選択
(3) ALT+TAB で nyagos 選択
(4) キー入力 （←最初の文字が２つ入力されます）

【環境】
OS : Windows 10 Pro バージョン 1903  (OSビルド 18362,1139)
nyagos : 4.4.8_0
（※ 4.4.5_4 のときは本現象は発生していませんでした）

私の環境の問題かもしれませんが・・、お手数をおかけしますが再現するか確認していただけないでしょうか。

**Comment by zetamatta** [comment]
常にというわけではありませんが、発生を確認しました。
おそらくですが、 旧 #390 (なぜか消えてしまったので、通知メールを元に #394 に一部復元) で行った

* U+2xxx 台の Unicode をコピペできない問題

への対処が影響しているのではないかと見ています。

これは「U+2xxx 台のUnicode をペーストした時、キーを離した時のコードは発生するが、キーを押した時のコードが何故か発生しない」というコマンドプロンプトのおかしな挙動※の回避策です（※ おそらくですが、[Windows10 の 1803 ～ 1909 のどこかのバージョンで入った不具合ではないかと見ています](https://twitter.com/NyaosOrg/status/1311183641880322048) )

この時の対応としては通常はキーを押した時だけキーが入力されたとしているのを、ある条件が成立した時だけはキーが離された時もキーが入力されたと解釈することで回避しています。

これが本件の誤動作の原因になっている可能性があると見ていますが、本件、下手な再修正をすると、逆にまた U+2xxx のコードが入力できなくなるおそれがあること、また、この処置自体は自分のレポジトリではなく、利用しているライブラリ [mattn/go-tty](https://github.com/mattn/go-tty) の方に[回避コードを入れていただいたりした](https://github.com/mattn/go-tty/pull/38)ので、あまり安易には直しづらいという状況です。

本件、時間かかりそうですが、慎重に対応させてください。

**Comment by tostos5963** [comment]
確認ありがとうございます。承知いたしました。

**Comment by zetamatta** [comment]
@tostos5963 

使用ライブラリ(mattn/go-tty)に修正パッチをマージしていただきました。→ https://github.com/mattn/go-tty/pull/40
これをリンクし、問題が解消されたのを確認しています。

nyagos の次のバージョンより公式バイナリに反映されますが、ソースの方は修正済みなので、よろしければ以下よりスナップショットのバイナリをダウンロードして、ご確認ください

* for amd64
    * https://ci.appveyor.com/project/zetamatta/nyagos/builds/36425471/job/on9t2gd7cw8dqff5/artifacts
* for 386
    * https://ci.appveyor.com/project/zetamatta/nyagos/builds/36425471/job/47tpnteo0kjpw7e3/artifacts

**Comment by tostos5963** [comment]
ありがとうございます！
問題解消されていることを確認できました。

**Comment by zetamatta** [comment]
本修正を反映したバイナリ、[4.4.9_0](https://github.com/zetamatta/nyagos/releases/tag/4.4.9_0) を公開しました。
