### ISSUE TITLE
nyagosでluaを呼び出すときのPATHについて

### ISSUE THREAD

**Issue by ironsand** [zetamatta/nyagos#398]
```
suffix.lua={"nyagos.exe","-f"}
```
を`~/.nyagos`に置いてluaのファイルを実行できるようにしてるのですが
scoopでインストールしている外部コマンドを実行しようとするとエラーになります。

```
handle = io.popen("hugo new hoge.md")
handle:close()
--> attempt to index a non-table object(nil) with key 'close'
```
以下の設定でnyagosではなくlua(5.4.2)を使ったときは期待通りに動作します。
```
suffix.lua={"lua"}
```
おそらくPATH周りの問題だと思うのですが、nyagosでluaのスクリプトを動かすときに環境変数を受け継いで実行するにはどうすればいいでしょうか？

nyagosのバージョンは` 4.4.9_2-windows-amd64 by go1.15.6`になります。

**Comment by zetamatta** [comment]
@ironsand さん：

環境変数の問題ではなく、`io.popen` の非互換性のせいではないかと思います（不具合でした…すみません）

    handle = io.popen("hugo new hoge.md")

を

    handle = io.popen("hugo new hoge.md","r" )

としてみていただけないでしょうか。本家 Lua の仕様では io.popen の第二引数は省略時に "r" と解釈されなければいけないのですが、nyagos の io ライブラリは事情があって自前実装となっていて、この省略時の動作仕様が実装から漏れてしまっていたようです（この不具合自体は次のリリースで修正したいと思います）

以上、ご確認のほど、よろしくお願いいたします。

**Comment by ironsand** [comment]
なるほど、そうだったんですね。ありがとうございます。
`r`オプションを付けて試してみたところ期待通りに動作しました。
