### ISSUE TITLE
nyagos.historyがないとクラッシュ

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#40]
` ~/AppData/Roaming/NYAOS_ORG/nyagos.history`が存在しない、もしくは空ファイルだと
何かコマンド実行時にクラッシュします。

**Comment by zetamatta** [comment]
ご報告ありがとうございます。ReadLine の汎用化の際にエンバグをしてしまったようです。

**Comment by nocd5** [comment]
修正ありがとうございます。 6f8bb2e262f73a34f6a3c5c15e6d05f3ece05e7e で修正されていること確認できました。
