### ISSUE TITLE
"echo !xxx" causes unexpected end of nyagos.

### ISSUE THREAD

**Issue by masamitsu-murase** [zetamatta/nyagos#402]
When I enter "echo !xxx" on nyagos, nyagos exits unexpectedly as follows:

```bash
$ echo !xxx
!xxx: event not found
exit status 1
```

I checked this issue with nyagos 4.4.9_3.

It seems that this issue is caused by d5ca8a4f96336145c4b3a220dfb2970b293b8a5c.
When `Replace` in `history/history.go` fails to replace `!xxx` in command line, the error is propagated to `ForEver` in `shell/loop.go`.
Then, the error ends `for` loop in `ForEver` in `shell/loop.go`.

**Comment by zetamatta** [comment]
Thank you.（ありがとうございます）

> It seems that this issue is caused by d5ca8a4.

Right.

d5ca8a4 can not be reverted for #383 and other unexpected errors.
So, I fixed the called subroutine to display the error only but not to quit the shell on c3cae8392338a9bdcf18a38c1f6bb279f322ef8b

（そのとおりでした。とはいえ #383 や他の予期せぬエラーのために d5ca8a4 を消すわけにはいかないので、もっと下流の方で、ヒストリーのエラーを表示するだけにとどめておくよう修正しました）

**Comment by masamitsu-murase** [comment]
Thank you so much for your prompt response!
I verified that your fix, c3cae8392338a9bdcf18a38c1f6bb279f322ef8b, worked fine!

Let me close this issue.
