### ISSUE TITLE
"ls -a" や "echo text" のようなオプション付きのコマンドが-cオプションで指定時に実行できない

### ISSUE THREAD

**Issue by tomato3713** [zetamatta/nyagos#403]
-cオプションでコマンドを実行しようとした際に、`nyagos -c 'ls'`のようにオプション無しの状態ではコマンドを実行できましたが、タイトルのように`nyagos -c 'ls -a'`のようにオプションをつけるとコマンドが認識できないとのエラーメッセージが表示されました。

```
$ nyagos -c "echo text"
'echo text' is not recognized as an internal or external command,
operable program or batch file
$ nyagos -c "ls -a"
'ls -a' is not recognized as an internal or external command,
operable program or batch file
```

```
$ nyagos -c 'ls'
Doc/          alias/        completion/   functions/    installer/    makeicon.cmd* nyagos.syso   t/
Etc/          appveyor.yml  defined/      go.mod        main.go       nodos/        readme.md     texts/
LICENSE       bin/          demo.gif      go.sum        mains/        nyagos.d/     readme_ja.md
_nyagos       commands/     frame/        history/      make.cmd*     nyagos.exe*   shell/
```

## 環境

- Nihongo Yet Another GOing Shell 4.4.8_0-25-g9d5c77b1-windows-amd64 by go1.15.3
(c) 2014-2020 NYAOS.ORG <http://www.nyaos.org>
- Windows Terminal バージョン: 1.6.10571.0

## 経緯
NeoVimで `set shell=nyagos.exe`としてnyagosを使おうと設定を調べていた時に気づきました。

**Comment by zetamatta** [comment]
```
$ nyagos -c "ls -a"
```

ではなく

```
$ nyagos -c ls -a
```

ならば、オプションを認識できると思います。こうなったのは、

- [Incompatible cmd command invokation option · Issue #359 · zetamatta/nyagos](https://github.com/zetamatta/nyagos/issues/359)

でコマンド名に空白が含まれるようなコマンドを実行させるために、可変長引数的に引き渡し可能にしたためです。
（ `CMD /? ` の２ページ目くらいで表示されるような、CMD.EXE 同様の柔軟な解釈をさせるべきか…悩ましいところです）

**Comment by tomato3713** [comment]
返信ありがとうございます。

確かに、
```
$ nyagos -c ls -a
```
だとオプションを認識して実行できました。

https://github.com/zetamatta/nyagos/blob/master/Doc/02-Options_en.md#-c-command
にオプション付きの場合の例を追加したほうが良いかもと思いました。

NeoVimのshellでCMD.exe同様にnyagosを使うのは難しそうですね。
もし、うまくいく設定をご存じでしたら教えていただけると助かります。

**Comment by zetamatta** [comment]
少々、おまちいただけますか。

CMD.EXE の場合、自分に与えられたパラメータ中の二重引用符の存在をちゃんと把握していて、それによって第一引数がコマンド名だけか、続く引数も含んだものなのか、細かい判断をしています。一方、nyagos の場合、Go言語のコマンドラインパラメータの入った配列：os.Args 経由でパラメータを得ていたため、二重引用符が既にはぎとられていて、同じ真似ができませんでした。

が、先程、os.Args に加工される前の生コマンドラインを得る手段の目処がたったので、CMD.EXE の真似事ができるかもしれません。ちょっとトライしてみます。

**Comment by zetamatta** [comment]
（経過報告）お待たせしております。下記のとおり対応中です。暫くローカルで試用の後、公式バイナリをリリースしたいと思います（スナップショット → [amd64](https://ci.appveyor.com/api/buildjobs/mym90gtmkfdwh03t/artifacts/bin%2Fnyagos-amd64-1.0.1571.zip) , [386](https://ci.appveyor.com/api/buildjobs/fh22mdj2a3sfn06m/artifacts/bin%2Fnyagos-i386-1.0.1571.zip) ）

### （１） [(#403) Support -s, -c and -k like CMD.EXE · zetamatta/nyagos@0ff7cdd](https://github.com/zetamatta/nyagos/commit/0ff7cdd25ad38493d2c88eefde44d2c1c3baf2dd)

CMD.EXE の次の仕様と「だいたい互換のはず」の -c , -k , -s オプションを追加
（※ nyagos では CMD.EXE と違い、オプションマークが `/` ではなく `-` になっている点に注意）

**CMD.EXE /? の２ページ目より**

```
/C または /K が指定されている場合、スイッチの後の残りのコマンド ラインが
コマンド ラインとして処理されます。次のルールが引用符 (") の処理に使われます:

    1.  次のすべての条件に一致する場合、コマンド ラインの引用符が有効になり
        ます:

        - /S スイッチがない
        - 引用符が 1 組ある
        - 引用符の中に特殊文字がない
          (特殊文字は &<>()@^| です)
        - 引用符の中に 1 つ以上のスペースがある
        - 引用符の中の文字列が、実行可能ファイルの名前である

    2.  最初の文字が引用符であるにも関わらず上の条件に一致しない場合は、最初
        の引用符とコマンド ラインの最後の引用符が削除され、最後の引用符の後
        のテキストが有効になります。
```

分かりづらい内容ですが、要は

1.  → `nyagos -c "ls" "-l "C:\Program Files"` といったマルチパラメータでの呼び出し
2.  → `nyagos -s -c "ls -c "C:\Program Files""` といったシングルパラメータでの呼び出し

となります。2. の場合、os.Args では二重引用符が削除された後のパラメータしか得られないので、[go-windows-commandline](https://github.com/zetamatta/go-windows-commandline) というパッケージを別途作成し、生のパラメータを取得するようにしています。

### （２） [Fix the problem that some irregular double-quotations were removed · zetamatta/nyagos@8048269](https://github.com/zetamatta/nyagos/commit/804826950600127ffe74edce14130d6fc43124b1)

 `nyagos -s -c "ls -c "C:\Program Files""` という呼び出しが、CMD.EXE → nyagos で行われる分には問題ないのですが、nyagos → nyagos で行う場合 Files 以下が欠けてしまうという、外部コマンド呼び出し時の不具合がありました。

原因はnyagos内部の shell パッケージの、二重引用符の対応関係がイレギュラーな時にコマンドラインの再組み立てがおかしくなってしまう不具合でした。不具合自体は修正したものの、対象箇所が結構クリティカルな場所なので、しばらく妙なエンバグになっていないか試用する予定です。

**Comment by tomato3713** [comment]
ご対応していただき，ありがとうございます．
自分のほうでもスナップショットを試用してみて，問題がないか確認してみようと思います．

何か気が付いた点があれば，報告させていただきます．

**Comment by zetamatta** [comment]
[Release 4.4.9_5](https://github.com/zetamatta/nyagos/releases/tag/4.4.9_5)にて、不具合修正を反映いたしました。以上、よろしくお願いいたします。

**Comment by tomato3713** [comment]
承知しました．ご対応ありがとうございます．
