### ISSUE TITLE
Release 4.4.9_4とRelease 4.4.9_5の suffix の挙動の違いについて（"_nyagos"）

### ISSUE THREAD

**Issue by tGqmJHoJKqgK** [zetamatta/nyagos#406]
Release 4.4.9_4 ⇒ Release 4.4.9_5 に更新した際に、
以下の挙動の違いに気が付きました。念のためご報告いたします。

#403 に絡むものかなぁと考えております。
仕様変更でしたら、申し訳ありません。

**環境**
エディション	Windows 10 Home
バージョン	20H2
OS ビルド	19042.928
Nihongo Yet Another GOing Shell 4.4.9_4-windows-amd64 by go1.16
Nihongo Yet Another GOing Shell 4.4.9_5-windows-amd64 by go1.16.3

**再現手順**
[1] [.NET Core SDK](https://dotnet.microsoft.com/download/dotnet/3.1)をダウンロードしてインストールする。
[2] [Release 4.4.9_4](https://github.com/zetamatta/nyagos/releases/tag/4.4.9_4)と[Release 4.4.9_5](https://github.com/zetamatta/nyagos/releases/tag/4.4.9_5)のNyagosをダウンロードして展開する。
[3] 展開したフォルダの "nyagos.exe" と同じ階層にある "_nyagos" ファイルを以下の内容に編集する。
```
# This is a configuration for NYAGOS
# The syntax is like a batchfile of command.com.

if     "%OS%" == "Windows_NT" set "PROMPT=$L%COMPUTERNAME%:$P$G$_$$$s"
if not "%OS%" == "Windows_NT" set "PROMPT=$L%NAME%:$P$G$_$$$s"

rem vim:set ft=dosbatch:

suffix >nul 2>nul

if not errorlevel 1 then
  suffix "fsx=dotnet fsi --nologo"
end

```
[4]  "nyagos.exe" と同じ階層に "test.fsx" という名前の空ファイルを作成する。
[5] Release 4.4.9_4 と Release 4.4.9_5 それぞれの "nyagos.exe" を起動し、"test.fsx" と入力してエンターキーを押下する。
　  Release 4.4.9_4とRelease 4.4.9_5 で挙動が異なることが確認できる（※）。
　  ※初めて実行した際は .NET Core の初回メッセージが表示されるため、2回目以降で比較する。

**Release 4.4.9_4**
何も表示されず終了する。

**Release 4.4.9_5**
以下のメッセージが表示される（suffix が "dotnet" になっている？）
```

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

```
**期待する挙動**
Release 4.4.9_4以前の "_nyagos" ファイルが使用できること。

**Comment by zetamatta** [comment]
@tGqmJHoJKqgK さん：

ご報告ありがとうございます。完全に不具合です。

「suffix 文を実現している引数フィルター機能 (ArgsFilter) 機能に、二重引用符をとっぱらう前の引数を加工する機能が抜けているという機能不足の問題」を #403 の修正がモロに踏んでしまったようです。

至急対応いたしますので、少々お待ちいただけますでしょうか。

**Comment by tGqmJHoJKqgK** [comment]
ご回答いただき、ありがとうございます！

お手数ですが、ご対応よろしくお願いいたします。。。
"_nyagos" の suffix 設定が全滅したので仕様変更だったら、どうしようと悩んでいるところでした。。。
現状、suffixを使用しなければ問題はないため、気長にお待ちしております！

**Comment by zetamatta** [comment]
nyagos.argsfilter で生のパラメータがコンバートされず、suffixコマンドが期待どおり機能しなくなっていた不具合を修正いたしました。

* [Release 4.4.9_6 · zetamatta/nyagos](https://github.com/zetamatta/nyagos/releases/tag/4.4.9_6)

> suffix "fsx=dotnet fsi --nologo"
> test.fsx

で dotnet コマンドの説明表示しか出なくなっていたのは、本来 `dotnet fsi --nologo test.fsx` と置換されるべきものが、コマンド名以外の生のパラメータが欠けてしまって `dotnet` だけになってしまっていたからでした。

（ここで生のパラメータというのは `"foo"` 、逆に生でない加工済みパラメータというのは二重引用符をのぞいた `foo` といったものになります。従来は生のパラメータが欠けても、加工済みパラメータの方から外部コマンドにわたすパラメータを作成していたのですが、4.4.9_5 で二重引用符の位置などを正確に外部コマンドに引き渡す必要が出てきたため、加工済みパラメータではなく、生パラメータを外部コマンド向けにも使うようになりました。その結果、ずっと前からあった引数フィルターを通すと生パラメータが欠けるという問題が表面化してしまったわけです…複雑でわけのわからない話で恐縮です）

以上、ご確認の程、よろしくお願いいたします。

**Comment by tGqmJHoJKqgK** [comment]
Release 4.4.9_6 の suffix を確認いたしました。問題ございません。
迅速に対応してくださり、ありがとうございました！！


今回の事象に関する詳細な解説まで、ありがとうございます。。。

以前から生パラメータは欠けることがあったが、従来は加工済みパラメータを
もとにしていたため顕在化しなかった。
4.4.9_5で、生パラメータをもとにするように変更が入ったため、
従来からある生パラメータが欠ける問題が顕在化したとのこと承知しました。

**Comment by zetamatta** [comment]
@tGqmJHoJKqgK さん：

感謝するのはこちらです。本当にありがとうございました。
不具合抱えたままずっと放置になって、評判が知らぬ間に落ちていっていつの間にか誰にも使われなくなる…ということを一番おそれております。この度はリリースして早々にご連絡いただけて助かりました。
（特に本件は自分の不注意・迂闊さが原因なので、余計に…です。説明をたくさん書いたのは弁解のようなもので、お恥ずかしい限りです）

一旦、本 issue はクローズとさせていただきますが、また動作がおかしい点など見受けられましたら、ご連絡いただければと存じます（本件がちゃんと直っていないようであれば Reopen していただけば結構です）

今後ともよろしくお願いいたします。
