### ISSUE TITLE
nyagos-4.4.9_6-windows-amd64.zipにDocディレクトリが入っていない

### ISSUE THREAD

**Issue by orz--** [zetamatta/nyagos#407]
実害は無いですが、readmeやDocディレクトリが含まれてなかったです。

**Comment by zetamatta** [comment]
ありがとうございます。

実は…ブラウザで GitHub を見られるし、ドキュメントをいちいちアーカイブに入れると、展開する時邪魔になるだけかなと思って、今回から除いてみたのですが…やはり、これは…入れた方がよいでしょうか？
（変更履歴に書いておけばよかったです。申し訳ありません）

**Comment by orz--** [comment]
なるほど承知いたしました。
自分はgithubで修正内容を見てからダウンロードしているので問題ないです！

**Comment by zetamatta** [comment]
ご連絡ありがとうございました。

とりあえず、Releaseページにドキュメントを省いた旨を追記しました。次のリリースでも省くか、あるいは再度添付するかは、また再検討したいと思います。

以上、よろしくお願いいたします。
