### ISSUE TITLE
 "#" で始まる引数を引用符なしで使用した場合の挙動について

### ISSUE THREAD

**Issue by 8exBCYJi5ATL** [zetamatta/nyagos#408]
tGqmJHoJKqgKです。
現在、元のアカウントにログインできない状況のため、
別アカウントから失礼いたします。

先日は迅速な対応をしてくださりありがとうございました。
zetamattaさんのコメントを拝見し、感銘を受けました。

以下の事象は後述の解決方法にて、ユーザー側で
回避可能なため、これまで問題視しておりませんでした。

図に乗って、こちらもあげさせていただきます。。。
"#" が特殊文字だったらすみません。。。

### **環境**
エディション Windows 10 Home
バージョン 20H2
OS ビルド 19042.928
Nihongo Yet Another GOing Shell 4.4.9_6-windows-amd64 by go1.16.4
※ 過去のバージョンでも再現可能です。少なくとも [Releases 4.4.4_0](https://github.com/zetamatta/nyagos/releases/tag/4.4.4_0) で再現できます。

### **再現手順**
1. [Nyagos](https://github.com/zetamatta/nyagos/releases/tag/4.4.9_6)をダウンロードして展開する。
2. 展開したフォルダにある "nyagos.exe" を起動して、以下のコマンドを実行する

**◆ ケース1**
```
echo 1 # 2
```
**期待する実行結果**
```
1 # 2
```
**実際の実行結果**
```
1
```

**◆ ケース2**
```
echo #123
```
**期待する実行結果**
```
#123
```
**実際の実行結果**
```

```

### **暫定的な解決方法**
以下の内容を記述したテキストファイルを "zz_01_userscript.lua" という名前で保存し、
"nyagos.exe" と同じ階層にある "nyagos.d" フォルダに配置する。
※ 全既存ファイルよりも後で読み込まれるファイル名であれば何でもよいはず。
```lua
nyagos.argsfilter = function(args)
  for i = 1, #args do
    args[i] = string.gsub(args[i], "%[%[%[%^SHARPREP%]%]%]", "#")
  end
  if share._org_suffix_argsfilter then
      local args_ = share._org_suffix_argsfilter(args)
      if args_ then
          args = args_
      end
  end
  local m = string.match(args[0],"%.(%w+)$")
  if not m then
      if 1 == 1 then return args end
  end
  local cmdline = share._suffixes[ string.lower(m) ]
  if not cmdline then
      if 1 == 1 then return args end
  end
  local path=nyagos.which(args[0])
  if not path then
      if 1 == 1 then return args end
  end
  local newargs={}
  if type(cmdline) == 'table' then
      for i=1,#cmdline do
          newargs[i-1]=cmdline[i]
      end
  elseif type(cmdline) == 'string' then
      newargs[0] = cmdline
  end
  newargs[#newargs+1] = path
  for i=1,#args do
      newargs[#newargs+1] = args[i]
  end
  return newargs
end

nyagos.filter = function(args)
  return string.gsub(args, "#", "[[[^SHARPREP]]]")
end

```

**Comment by zetamatta** [comment]
ご指摘ありがとうございます（返答遅くなりました。すみません）

単語の先頭になる `#` 以降をカットしてしまう動作は bash の仕様を模したものになります。

```
$ echo 1 \# 2
1 # 2

$ echo 1 .# 2
1 .# 2
```

なので、一応は設計動作ということになるのですが、もしなんらかの不都合が多いようでしたら、対応検討いたしますが、どうでしょうか？
（動作を変えるスイッチを設けるか、あるいは先頭以外の `#` は普通の文字として処理するか…あまり CMD.EXE とも bash にもない仕様は必要最小限にした方がよいのではありますが。ここは利便性とのバランスだと思います）

以上、よろしくお願いいたします。

**Comment by 8exBCYJi5ATL** [comment]
ご回答いただき、ありがとうございます。

>単語の先頭になる # 以降をカットしてしまう動作は bash の仕様を模したものになります。

なるほど。。。
教えてくださり、ありがとうございます。
納得しました！

>もしなんらかの不都合が多いようでしたら、対応検討いたしますが、どうでしょうか？

現行のままで、問題ございません。
これまで通り、lua による機能拡張で対応いたします。

この件は、個人で作成したCLIアプリで、引用符なしでスペースを含むファイル名を
指定できるような機能を作った際に、CMD.EXE では処理できるファイルが、
Nyagos だと no such file or directory になることから気が付きました。

この挙動について調べたのですが、bash がこの挙動であることに気が付かず、
これまで、気になっておりました。仕様通りであることを教えていただき、すっきりしました！

お手数をおかけして、申し訳ありません。
ご回答いただき、ありがとうございました。
