### ISSUE TITLE
glob  doesn'twork for command alias

### ISSUE THREAD

**Issue by juggler999** [zetamatta/nyagos#409]
日々Nyagosの上で暮らしています．素晴らしいシェルをありがとうございます．
以下，気づいた症状を報告します．投稿ははじめてですので，不手際があれば容赦ください．

Ver: 4.4.9_6
症状: aliasしたコマンドのときにグロブが効かない
例:
    % alias some_script="perl c:/usr/bin/some_script.pl"    (A)
    % some_script *                                                              (B)
このとき，(B)で some_script は *  を展開しません．
もちろん，set -o glob または nyagos.option.glob = true しています．
4.4.9_6より前では上のケースできちんとグロブを展開していました．
なお(A)を
    % alias some_script="wildcard perl c:/usr/bin/some_script.pl"
とすれば (B) は期待どおりに動作します．

**Comment by zetamatta** [comment]
ご連絡ありがとうございます。**症状確認いたしました。**

おそらく、4.4.9_5 で発生した不具合（たぶん、#406 同様に #403 が起因）ではないかと思われます。
調査・修正いたしますので、少々お待ちいただけますでしょうか。

よろしくお願いいたします。

**Comment by zetamatta** [comment]
とりいそぎ修正しました。`set -o glob` によるワイルドカード展開そのものが効かなくなっていたようです。

* 実行ファイル：スナップショット
    * [amd64](https://ci.appveyor.com/api/buildjobs/le685s3oxuopnpsx/artifacts/bin%2Fnyagos-amd64-1.0.1585.zip)
    * [386](https://ci.appveyor.com/api/buildjobs/cgv7qt90lf191ath/artifacts/bin%2Fnyagos-i386-1.0.1585.zip)

（内部的に「二重引用符をカットした加工済み引数」の配列と「入力されたそのままの生の引数」の配列の２つで管理しているのですが、ワイルドカード展開の際に後者の展開が漏れてしまっていました。#403 以前だと「加工済み引数」で「生の引数」を逆生成する処理があったので表面化していなかったのですが、 #403 でイレギュラーな二重引用符の対応が必要になったため、できるだけ最初に入力された「生の引数」を利用しようとした結果、本不具合が発生してしまいました）

特に問題がないようであれば、そのまま次回のリリースに反映したいと思います。

**Comment by juggler999** [comment]
早速のご対応と詳しい説明をいただきありがとうございます．
# タイトルの一部がおかしくてすみませんでした．

最初にお示ししたaliasの例で"wildcard"をはずしていくつか試したところ，いずれも従来と同様にうまくワイルドカードを展開してくれています．

次回のリリース，ゆっくりとお待ちしています．

**Comment by zetamatta** [comment]
[Release 4.4.9_7 · zetamatta/nyagos](https://github.com/zetamatta/nyagos/releases/tag/4.4.9_7) にて本修正を取り込んだ対応版を公開いたしました。

よろしくお願いいたします。

**Comment by juggler999** [comment]
ありがとうございます．期待どおり動いています．

**Comment by zetamatta** [comment]
ご確認ありがとうございます！
