### ISSUE TITLE
French Keyboard

### ISSUE THREAD

**Issue by malys** [zetamatta/nyagos#41]
I want to congratulate you for your nyagos. I'm using your software with a French keyboard and I don't understand why but some character doesn't work when I'm typing.
ex: @ (altgr + 0)
See French keyboard layout
![French keyboard layout](http://upload.wikimedia.org/wikipedia/en/c/c4/French_pc_keyboard.svg)

It's possible that was an issue with 'altgr'

**Comment by zetamatta** [comment]
Thank you for reporting the problem.
I want to find the reason why some keys does not work on French keyboard.

**Comment by zetamatta** [comment]
NYAGOS.exe considered CTRL-ALT-XXX (= AltGr-XXX) as same as ALT-XXX.
It is possible that this behavior is the reason of French keyboard problem.

On [Test version](https://github.com/zetamatta/nyagos/releases/tag/20150117-issue41-1),NYAGOS.exe cosideres CTRl-ALT-XXX (= AltGr-XXX) as different code as ALT-XXX. Could you test it ?

(Commit code is 8339d81e3104bfd15da3a750e1159a95abc6f7f6 )

**Comment by malys** [comment]
Perfect!!!!
Many thanks for your reactivity...
I'm looking for a advanced .nyagos example to start  a customization of my nyagos. Could you provide it in the repository or your website?
Many  thanks!!!

**Comment by zetamatta** [comment]
Thank you for testing and reporting !
I merged the new codes to fix this problem ( 8339d81e3104bfd15da3a750e1159a95abc6f7f6 ) to the master branch.

I accept your request about an advanced .nyagos example. Now I created the issue #42.

For your information,  a NOT ADVANCED .nyagos example is [HERE](https://gist.github.com/zetamatta/d2d6298d24960c41f4e2 ).
It is copy of my `%USERPROFILE%\.nyagos`.
