### ISSUE TITLE
East Asian Ambiguous Character

### ISSUE THREAD

**Issue by juggler999** [zetamatta/nyagos#412]
最近気づいたのですが，罫線などの"East Asian Ambiguousな文字"の表示がおかしくなっていませんでしょうか?
例えば，
        └─        (U+2514, U+2500)
はOKなのですが，
        ─┐        (U+2500, U+2510)
では表示が乱れます．以前のNyagos+Cmderではうまく表示されていました．

テスト環境
NYAGOS: 4.4.10_2
OS: Windows10 (21H1)
フォント: MeiryoKe_Console
ターミナル:
    Cmder Version 1.3.18
    Windows Terminal
    cmd.exeコンソ-ル
    (※三者三様の乱れ方)
コードページ: 65001
 
もっともcmd.exeコンソール+cmd.exeシェルでもおかしいので，East Asian Ambiguousな文字は難しいのかもしれませんが．
ただ，以前のNYAGOS+Cmderでは完璧だったのでここに報告しました．

**Comment by juggler999** [comment]
ご連絡とご対応，たいへんありがとうございます．
 
   OS: Windows10 (21H1)
    cmd.exeのコンソール+cmd.exeシェル (A) 
    cmd.exeのコンソール+Nyagos(新) (B, (386))，及びnyagos4.4.10_2 (C)
であらためて試してみました．

    ┐ (U+2500) 
単独では2セル幅(1全角幅)にみえますが，
    ─┐ (U+2500, U+2510)
の組合わせでは4セル幅(2全角幅)ではなく，それよりも短い幅で表示されるようです((A)～(B)のすべてで)．
これは上で書かれた「常に無理やり２セル分移動させるようにしました」とは異なるようです．

UAX#11ではUnicode のテキストを東アジアの従来文字コードの文脈で扱う場合，特性値A（曖昧）を持つ文字は全角の文字として扱う，とされているようですが，日本語版Windows10のcmd.exeではこれには従っていないということかもしれません．

※Nyagosとcmd.exeの役割分担を理解できていないのでピントが外れているかもしれませんが．

**Comment by zetamatta** [comment]
「表示」とは具体的に、どのような手順で表示させた場合でしょうか？

今回、nyagos で対応したのは「コマンドライン（＝プロンプトのある行）の入力上の取り扱い」となります。ここで文字幅・カーソル位置などが狂ってしまうと「入力したコマンドの編集」が不能になってしまうため、カーソル位置を微調整するなどして無理やりにでも対応する必要がありました。

が、それ以外についてはターミナル側、もしくはターミナル上で動く各個別のアプリケーションの領域になるため、基本的には nyagos ではどうしようもありません（ nyagos もまたターミナルの上で動く１アプリケーションに過ぎないので、自分の表示は調節できても他のアプリは… ）

以下は、nyagos のコマンドラインから `echo ` とタイプしてから、その後 `─┐ `  (U+2500, U+2510)をブラウザからコピペし、Enter を押した結果になります。

![image](https://user-images.githubusercontent.com/3752189/131214097-b1a594e9-7906-41aa-b909-871acd1f8018.png)

この例でいうと、コマンドライン上では罫線文字を表示させる時に、罫線１文字あたり画面の領域２セルを使うようにカーソル位置を調整しています。罫線文字は２つあるので、コマンドライン上では結果４セル分：8ピクセル×２セル = 32ピクセルをしめています。

一方で echo コマンドの出力についてはそういう調整がないので、2文字表示しているのに24ピクセル=3セル分しか使われないという「おかしな症状」が出ています。こちらは基本的にもう対応範囲外だと思っていただいた方がよいと思います。
（echo コマンドに限って言えば、一応 nyagos の内蔵コマンドなので調整できなくもありませんが、echo だけ直してもあまり意味がないと思われます）

以上、ご確認のほど、よろしくお願いいたします。

**Comment by juggler999** [comment]
ていねいなご説明，ありがとうございます．
私がずっと言っているのは，コマンドライン上ではなく，くだんの文字列を含むテキストをコンソール上に表示した場合でした．
例えば，cat TEXT, type TEXT, echo TEXT, lv TEXTなどです．
Nyagosの扱い得る範囲外のようである，Windowsが合理的に対応するのを待つほかない，と理解しました．

**Comment by zetamatta** [comment]
本件、一旦クローズさせていただきます。よろしくお願いいたします。
