### ISSUE TITLE
Feat: Integration https://github.com/microsoft/inshellisense

### ISSUE THREAD

**Issue by malys** [zetamatta/nyagos#439]
Hi, 
I have tried to integrate **inshellisense** in my legacy autocompletion system. (see is function)

```lua
-- autocompletion --
-- Convert url --
local function convert(url)
    if url == nil then
        return
    end
    url = url:gsub(" ", "%%20")
    url = url:gsub(".exe", "")
    url = url:gsub(".bat", "")
    url = url:gsub(".cmd", "")
    return url
end

-- Concat table --
local function tableConcat(t1, t2)
    for i = 1, #t2 do
        t1[#t1 + 1] = t2[i]
    end
    return t1
end

-- Remove duplicate entry in a table --
local function deduplicate(t)
    local seen = {}
    for index, item in ipairs(t) do
        if seen[item] then
            table.remove(t, index)
        else
            seen[item] = true
        end
    end
    return t
end

-- caching insert --
local function add_cache(init, cmd, prefix, pwd, sep)
    if sep == nil then
        sep = '[^ \n*>-/]+'
    end
    local bs = init;
    --	print(cmd)
    --	print (nyagos.eval(cmd))
    for b in nyagos.eval(cmd):gmatch(sep) do
        table.insert(bs, b);
    end
    share[prefix .. '_' .. pwd] = {
        data = bs,
        time = os.time()
    };
    -- print ('>>>add cache')
    -- print( bs)

    return bs;
end

-- cache manager --
local function caching(c, init, cmd, prefix, pwd, delay)
    if share[prefix .. '_' .. pwd] ~= nil then
        local diff = os.time() - share[prefix .. '_' .. pwd].time
        if diff > delay or delay == 0 then
            return add_cache(init, cmd, prefix, pwd)
        else
            return share[prefix .. '_' .. pwd].data;
        end
    else
        return add_cache(init, cmd, prefix, pwd)
    end

end

-- inshellisense management --
local function is(c)
    -- npm install -g @microsoft/inshellisense
    local cmd='is complete "' .. c.text .. '" | true'
    local arg= {}
    local output=nyagos.eval(cmd)
    if output ~='undefined' then
        for b in output:gmatch('"name":"([^"]+)"') do
            table.insert(arg, b);
        end
    end
    --    local description = {}
    --    for b in output:gmatch('"description":"([^"]+)"') do
    --        table.insert(description, '"'..b..'"');
    --    end

    --    local icon = {}
    --    for b in output:gmatch('"icon":"([^"]+)"') do
    --        table.insert(icon, '"' .. b .. '"');
    --    end

    --    local display = {}
    --    for i = 1, #arg do
    --        table.insert(display, icon[i] .. arg[i]);
    --    end

    c.isarg = arg
    -- c.isdisplay =  description
    return c
end


-- caching merge --
local function complete_cache (c, init, cmd, prefix, pwd, delay, concat)
    if concat ==false or concat ==nil then
        return caching(c, init, cmd, prefix, pwd, delay)
    else 
        return tableConcat(c.list, caching(c, init, cmd, prefix, pwd, delay))
    end
end


nyagos.completion_hook = function(c)
---  c.list[1] .. c.list[#c.list] - command/filename completion result
---  c.shownlist[1] .. c.shownlist[#c.shownlist] - text for list-up (Option)
---  c.word - original word without double-quotations.
---  c.rawword - original word which may has double-quotations.
---  c.pos - position word exists.
---  c.text - all command-line text.
---  c.field - array of the text splited c.text with space.
---  c.left - string before cursor

    local pwd = nyagos.getwd()
    local result={}
    if c.text:match('^git ') then
        result = complete_cache (c,autoGIT,'git branch && git tag -l && j unresolved','git',pwd,30);
   ...
    elseif c.text:match('^npm ') then
        if c.text:match('^npm run') then result = complete_cache(c, {}, "cat package.json | jq -r \".scripts| keys[]\" | sort | awk '{print $1}'", 'npmrun', pwd,
    12 * 60 * 60);
        else  result =  complete_cache (c,autonpm,"",'npm',pwd, 0);
        end        
    end
    result = tableConcat(result, is(c).isarg)
    if #result < 10 then
        nyagos.write("\n")
        r = {}
        local value=nyagos.box(result)
        table.insert(r,value)
        result=r
    end
    return deduplicate(result)
end
```

I'm not a specialist in lua and nyagos. Could you give me your feedback?

**Comment by hymkor** [comment]
As the result that I investigate [inshellisense], it may be difficult to integrate like [inshellisense] on the current version of nyagos in these points.

1. No feature to parse JSON text that `nyagos.eval('is complete "input"')` returns
2. No mechanism to intercept key input every time whatever the type of key is.

I am considering to implement some functions for 2 .
There may be other things you need, but I'd like to think about it each time.
(I will release 4.4.15_0 soon, so I will start after that is finished.)

[inshellisense]: https://github.com/microsoft/inshellisense

**Comment by hymkor** [comment]
I wrote the sample code. When the user pressed SPACE KEY as the trigger to start our original completion mode, Lua script iterates reading key and calling the function. You should insert the new code you want to do in the loop.

- The latest snapshot of NYAGOS ( sample requires )
    - [for amd64](https://ci.appveyor.com/project/zetamatta/nyagos/builds/49681821/job/k7ys984s29p946cd/artifacts)
    - [for 386](https://ci.appveyor.com/project/zetamatta/nyagos/build/job/p9840vh9uh30t8c4/artifacts)

```lua
nyagos.key[" "] = function(this) -- SPACE is the trigger to begin the interactive completion mode
    this:insert(" ")
    this:repaint() -- equals to `this:call("REPAINT_ON_NEWLINE")`
    while true do
        io.write("\027[?25h") -- cursor blink on
        local key=nyagos.getkeys() -- [New function] get the input-key-sequence
        io.write("\027[?25l") -- cursor blink off
        if key == " " then
            this:insert(" ") -- not to call itself recursively
            this:repaint()
        else
            local rc = this:eval(key) -- New function
            if rc == true then -- ReadLine ends with accept line (=Enter)
                return rc -- it ends our mode
            elseif rc == false then -- ReadLine ends with interrupt (=Ctrl-C)
                return rc -- it ends our mode
            end -- otherwise ReadLine continues
        end

        -- for example,when the commandline text is `GIT -`
        -- replace it to `git =`

        if string.sub(this.text,1,this.pos-1) == "GIT -" then
            this:replacefrom(1,"git -") -- replace string from the position specifyed with the 1st parameter to the position of cursor
            this:repaint()
        end
    end
end
```

The new functions: 
- `nyagos.getkeys` (not `getkey` ) the function which returns input-key-sequence like "\027[A" for ARROW-UP-KEY.
- Others are written in [docs/_07-LuaFunctions_en.md](https://github.com/nyaosorg/nyagos/blob/27555c073a784a73212f81c2371cd8a93a361894/docs/_07-LuaFunctions_en.md#nyagoskeykeyname--functionthisend-1)

**Comment by hymkor** [comment]
Thank you for your various opinions. I generally agree with the points you have made.

Nyagos has been under development for 10 years, but unfortunately, it has not gained much support or collaboration from many users and other developers. As I made feature expansions based solely on my own vision, it resulted in an increase of useless features that no one used, which made the program harder to maintain. 

Therefore, the policy going forward is to focus on maintenance and bug fixes, refraining from haphazardly adding features unless there are explicit requests from users. Feature expansions will only be made when there is a clear need confirmed from users.

There are various constraints for the nyagos ecosystem. Since maintaining compatibility with CMD.EXE as possible is one of the requirements, actively incorporating syntax from other shells like bash could lead to confusion in the specifications, so I consider that it should not be pursued aggressively. Additionally, as nyagos is developed in Go language, it is difficult to dynamically link and utilize libraries from other languages except for COM (OLE).

**Comment by hymkor** [comment]
I consider PowerShell 7.4 is not so bad. PowerShell can be configured with Emacs-style key bindings, and while the scripting has its quirks, I can get used to it.

But to tell the truth, I wish I could start from scratch and create a new shell in Rust with Lisp as the customization language. However, I've already rewritten the shell 3 times while changing platforms and languages, so I really can't do it anymore.
