### ISSUE TITLE
which コマンドの結果の途中に \\ が含まれる場合がある

### ISSUE THREAD

**Issue by pine613** [zetamatta/nyagos#51]
以下のように、内臓コマンド `which` の結果の途中に `\\` が含まれることがあるようです。

```
$ which powershell
C:\Windows\System32\WindowsPowerShell\v1.0\\powershell.exe
[~]
$ where powershell
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```

再現条件は、PATH の最後がスラッシュで終了している場合です。上記の場合、`C:\Windows\System32\WindowsPowerShell\v1.0\` が PATH に含まれています。

NYAGOS のバグ、というよりも Go 標準ライブラリ `exec.LookPath` の仕様みたいですが、気づいたので報告させていただきました。

**Comment by zetamatta** [comment]
ありがとうございます。LookPath の後で、パスをクリーニングする関数か何かあったと思いますので、それをかけてみます。

**Comment by zetamatta** [comment]
path.Clean , filepath.Clean では変わらなかったので、対応方法は要検討です。

where.exe があれば要らないかという気もしますが、一方で内蔵コマンド・alias などが出ないので、which でそれらを出せるように出来るようにしなくちゃいけませんね

**Comment by zetamatta** [comment]
- 4.0.6_0 で直っていなかった。

**Comment by zetamatta** [comment]
バイナリ公開後、２箇所の PC で直っていることが確認できたので、一旦クローズします。

なお、which.lua が nyagos.d に残っている場合、そちらが実行されてしまうおそれがあるのですが、こちらは一応別件扱いとします。

**Comment by pine613** [comment]
対応ありがとうございます!
