### ISSUE TITLE
lnk.js / vbs  not working as expected

### ISSUE THREAD

**Issue by NSP-0123456** [zetamatta/nyagos#59]
The lnk.js is not writing the link target if one parameter is set !

I did made a small change adding at the top :
```javascript
if( WScript.Arguments.length == 1  ){
  var wshShell=new ActiveXObject("WScript.Shell");
  var lnkSrc = wshShell.CreateShortcut(WScript.Arguments.Unnamed(0));
  WScript.Echo( lnkSrc + " ~> " +lnkSrc.TargetPath );
  WScript.Quit(1);
} 
```

**Comment by zetamatta** [comment]
Thank you! I merged your code.
(I modified your message-string a little. I hope there were no problems...)

**Comment by NSP-0123456** [comment]
I also forgot to prevent error if first argument is not an lnk file :disappointed: 
```javascript
if( WScript.Arguments.length == 1  ){
  var wshShell=new ActiveXObject("WScript.Shell");
  var lnkSrc = wshShell.CreateShortcut(WScript.Arguments.Unnamed(0));
  if( lnkSrc == null ){
     WScript.Echo("Fail to create ShortCut Object");
  } else {
    WScript.Echo( "    " + lnkSrc + "\n<-- " + lnkSrc.TargetPath ); 
  }
  WScript.Quit(1);
} 
```
almost same code should be done in lnk.vbs...

**Comment by zetamatta** [comment]
Thank you. I merged your code.

    almost same code should be done in lnk.vbs...

`lnk.vbs` have beet not included in the last nyagos package and repository.
