### ISSUE TITLE
Ctrl-Tでのカーソルの挙動が一般的でない

### ISSUE THREAD

**Issue by amuramatsu** [zetamatta/nyagos#64]
nyaosを含む他のshellと、Ctrl-Tでのカーソル移動が異なります。

* nyagos: カーソル位置が全く動かない
* bash, tcsh, nyaos: カーソル位置が一つずつ右にずれる、カーソルが行末にある場合だけカーソルが動かない

特に理由が無い限り、他のshellと挙動を合わせて欲しいです。

**Comment by zetamatta** [comment]
ご確認ください

https://github.com/zetamatta/nyagos/releases/tag/4.0.7_5
