### ISSUE TITLE
スペースのないリダイレクトで作成されるファイルが変

### ISSUE THREAD

**Issue by hokorobi** [zetamatta/nyagos#66]
echo a>a を実行すると aa という0バイトファイルが作成されます。
a という内容の a というファイル名で作成されることが期待されると思います。

困ってはいませんが気づきましたので。

Win7 + nyagos 4.0.7_4

**Comment by zetamatta** [comment]
ご報告ありがとうございます。
一応、ソース的には修正しました。特に深刻な不具合というわけでもなさそうなので、これが反映される次のバージョンのバイナリでご確認いただければ…と存じます。

よろしくお願いいたします。

**Comment by hokorobi** [comment]
はい、ありがとうございます。

**Comment by zetamatta** [comment]
[4.0.8_0 をリリース](https://github.com/zetamatta/nyagos/releases/tag/4.0.8_0)いたしました。ご確認ください

**Comment by hokorobi** [comment]
ありがとうございます、修正できていることを確認しました。
