### ISSUE TITLE
外部コマンドのリダイレクト時にコマンドが実行できない、または標準出力の内容が表示されない

### ISSUE THREAD

**Issue by hogewest** [zetamatta/nyagos#72]
外部コマンドの出力結果をリダイレクトした場合に正しくコマンドが実行できない、標準出力の内容が表示されない現象を確認しました。

確認環境
Windows7 + nyagos 4.0.8_0

コマンドが実行できない
```
$ where ping > hoge
エラー: 既定のオプションの値は空にはできません。
"WHERE /?" と入力すると使用法が表示されます。
```

標準エラー出力をNULで捨てると標準出力の内容が表示されない
```
$ where ping 2>NUL
$ 
```

nyagos 4.0.7_5 では問題ないようです(以下 4.0.7_5 での出力結果)
```
$ where ping > hoge
$ cat hoge
C:\WINDOWS\System32\PING.EXE
```

```
$ where ping 2>NUL
C:\WINDOWS\System32\PING.EXE
```

**Comment by zetamatta** [comment]
ご報告ありがとうございます。

リダイレクトマークの直前が空白だった時、０文字のパラメータが出来てしまう不具合がありました。

issue #66 「echo a>a で空の aa というファイルが出来てしまう」の修正時にエンバグしてしまったようで

     where ping > hoge

が

     where "ping" "" > hoge

のように解釈された結果、where が0文字の第二引数を受け取り、エラーを表示したようです。

一応、手元のソースでは既に修正済み（ [Fixed an empty argument was inserted before SPACE & REDIRECT-MARK](https://github.com/zetamatta/nyagos/commit/d938c446685023f1082c38fca45ff4ed5624e85e) )なのですが、なるべく早く反映されたバイナリをリリースいたしますので、少々お待ちいただけますでしょうか。

よろしくお願いいたします。

**Comment by hogewest** [comment]
ご対応ありがとうございます！

**Comment by zetamatta** [comment]
[4.0.9_0](https://github.com/zetamatta/nyagos/releases/tag/4.0.9_0) を公開しました。
お手数ですが、こちらでご確認いただけますでしょうか。

よろしくお願いいたします。

**Comment by hogewest** [comment]
修正されているのを確認しました。
ありがとうございました :smile:
