### ISSUE TITLE
入力文字列が横スクロールされた状態でCtrl-Uすると表示が崩れる

### ISSUE THREAD

**Issue by cagechi** [zetamatta/nyagos#88]
$ abcdef...
       ↓入力を続けるとwindow幅により自動でスクロールされる
$ efghijkl

この状態でCtrl-Uすると、プロンプト文字列が崩れたり、カーソルの位置がおかしくなったりします。
ご確認よろしくお願い致します。

NYAGOS 4.0.9_9 + Windows7

**Comment by zetamatta** [comment]
ご報告ありがとうございます。

そもそも、Ctrl-U がスクロール対応していませんでした。おそらく、大昔に「あとでやる」としていたものが、忘れてしまって、ずっとそのままになっていたと思われます。

5e82b0f40a453974f735a1994009dcbd822699cc にて対応しました。近日中に当修正を反映したバイナリも公開いたします。

**Comment by cagechi** [comment]
迅速なご対応恐れ入ります

**Comment by zetamatta** [comment]
当修正を反映した、4.0.9_10 を公開しました。

**Comment by cagechi** [comment]
ありがとうございます。
修正確認しました。
