### ISSUE TITLE
`nyagos.prompt`, `nyagos.alias`, `nyagos.on_command_not_found`の実行が排他になっていない

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#89]
`nyagos.prompt`, `nyagos.alias`, `nyagos.on_command_not_found`
この辺のluaを使うコマンド、フックなどの処理がぶつかるとpanicになるようです。

重めの処理の代わりにsleepを入れた再現パターン用`.nyagos`
https://gist.github.com/nocd5/2a0ed6c2dabf682e946a

```
$ foo | bar
```
を実行するとpanicで落ちます(`bar`は存在しないコマンド)。

以下デバッグした時のパッチですが
`Call`関数に入れてるmutexは、あるとdead lockしてしまうので実際はNGですが
挙動の違いは確認できると思います
https://gist.github.com/nocd5/f6f4fce05769fb299f53

**Comment by zetamatta** [comment]
実は認識してはいるのですが、「パイプライン実行時には使用不可とする」以外、対応方法が思いつかない状況です。UNIX のように fork があればよいのですが…

**Comment by zetamatta** [comment]
パイプラインで並行実行する時に、Lua インスタンス（Lua_State）の複製を取れればよいのですが、その方法がないのです…

**Comment by nocd5** [comment]
なるほどargshookのところはmutexでlockがかかってたので、処理忘れかと思いました。
自分の設定はpromptの処理が結構重いので、そこを排他にするだけでも落ちる確率はかなり減ったのですが。
そうか、パイプラインって使う方は逐次処理されるので順番に処理すればいいと思ってましたが、
実装上は並列でプロセス起動していなきゃないんですかね。

**Comment by zetamatta** [comment]
いや、ちゃんとしたパイプラインは逐次処理されるものではありません。パイプラインのバッファが「満タン」か「空」にならない限り、基本、同時に実行されるものです。（でないと UNIXでの「tail -f ファイル | grep パターン」などということができません）

nyagos.argsfilter は文字列処理しかなく、一瞬で処理が終わることが期待できるので、lock しても差し支えありませんでした。

このあたり、方式の限界を感じています…

**Comment by zetamatta** [comment]
Lua 側に「グローバル環境を元のスレッドと共有するが、 独立した実行スタックを持つスレッドを作る」lua_newthread という関数があることが分かったため、試しに使ってみました。

手元では提示いただいた例での panic が解消されたように見えますので、ご確認いただけますでしょうか。

(lua パッケージとは一応独立していた intepreter パッケージが lua 依存になってしまったため、もう少し手直しがいりますが、まずは試しに )

**Comment by zetamatta** [comment]
cd で落ちる不具合あり

**Comment by zetamatta** [comment]
どうも、lua_newthread は Lua のコルーチンのものであって、外部アプリケーションのスレッドのためのものではなかったようです（前にも同じような勘違いをしたのに、また繰り返してしまいました）

**Comment by zetamatta** [comment]
結果的に機能にかなり制約がかかってしまいますが、panic になるよりはマシなので

1. バックグラウンド実行
2. パイプラインの二つ目以降のコマンド
3. 1.、2. の中から間接的に呼び出されるコマンド

の時は Lua を呼び出そうとするとエラーになるようにしました。とりあえず、これでしばらく様子見です。

**Comment by nocd5** [comment]
ありがとうございます。挙げさせて頂いた再現パターンで落ちないこと確認しました。

しかし私が普段使っている設定だと
`nyagos.prompt`が原因だと思うのですが、依然落ちてしまいます。
ただ、最初に挙げた再現パターンの方は直っているので
いったんCloseしようと思います。

確認が遅くなりすいませんでした。

**Comment by zetamatta** [comment]
ご報告ありがとうございます。

もう、これは地道に潰してゆくしかないので、少々不完全な情報でも、issue 立てていたただければ、幸いです。
（しかし、理想を言えば、Lua を複数同時稼働できたらと思うんですが…難儀な問題です）

**Comment by zetamatta** [comment]
4.1-alpha で Lua インスタンス複数持ちに方式を改めたので、再度、当問題が解消されているかを確認します。

**Comment by zetamatta** [comment]
### .nyagos への修正

```
function share.sleep(n)
    local t = os.time()
    while os.time() - t <= n do end
end
share._prompt = nyagos.prompt
nyagos.prompt = function(template)
    share.sleep(1)
    return share._prompt('nyagos > ')
end
nyagos.alias.foo = function()
    print("alias.foo -->")
    share.sleep(1)
    print("<-- alias.foo")
end
nyagos.on_command_not_found = function(args)
    print("on_command_not_found -->")
    share.sleep(1)
    print("<-- on_command_not_found")
end
```

### テスト結果

```
nyagos > foo | bar
alias.foo -->
on_command_not_found -->
<-- on_command_not_found
<-- alias.foo'bar' is not recognized as an internal or external command,
operable program or batch file

nyagos > bar | foo
alias.foo -->
on_command_not_found -->
<-- on_command_not_found
<-- alias.foo'bar' is not recognized as an internal or external command,
operable program or batch file

nyagos >
```

Ok

**Comment by nocd5** [comment]
@zetamatta 
ありがとうございます。まだmultiluaの方はあまり試せておらず、環境もできていないのですが、折を見てこちらでも確認したいと思います。

**Comment by zetamatta** [comment]
すみません。そちらに通知が行くのを失念してました（別途、新規に起案すればよかったです）。

multilua の方は、 Lua の仕様がガラッと変わるので、バイナリリリースは慎重に進める所存です。

**Comment by nocd5** [comment]
自分が立てたissueですし、問題ありませんのでお気になさらないでください。
むしろmultiluaの方のステータスが分かったので良かったです。
