### ISSUE TITLE
Nyagos + Grunt = Super nodejs console on Windows

### ISSUE THREAD

**Issue by malys** [zetamatta/nyagos#91]
I'm using nyagos. I'm very satisfied.
Moreover, I use grunt-cli.
Including this command in bashrc on Linux, I can enable autocompletion for grunt task on Linux.

```bash
# Bash, ~/.bashrc
eval "$(grunt --completion=bash)"
```

Is it possible to integrate this mechanism in nyagos including a command in .nyagos?

Thank you for your job. ;)

**Comment by zetamatta** [comment]
Thank you for using NYAGOS !

> Is it possible to integrate this mechanism in nyagos including a command in .nyagos?

How about using nyagos.exec(),nyagos.atou() and nyagos.eval() ?

```
$ echo %FOO%
%FOO%
$ type foo.cmd
@echo set FOO=BAR
$ lua_e "nyagos.exec(nyagos.atou(nyagos.eval('foo.cmd')))"
$ echo %FOO%
BAR
$
```

In .nyagos,

```
nyagos.exec(nyagos.atou(nyagos.eval('BATCH-FILE-NAME')))
```

nyagos.atou() is the function which converts an ANSI-String to an UTF8-String because nyagos.eval() returns ANSI-String.

I hope my answer solve your problem.

**Comment by zetamatta** [comment]
Sorry, when foo.cmd echos more than one line, it does not work as expected.

It should be as below

```
lua_e "for line in nyagos.atou(nyagos.eval('foo.cmd')):gmatch('[^\n]+') do nyagos.exec(line) end"
```

**Comment by malys** [comment]
thank you for your help but I don't understand your solution.
I'm newbie in Lua and nyagos automation

but I had added this code in .nyagos

```lua
function fileExist(file_name)
  local file_found=io.open(file_name, "r")      
  return not (file_found==nil)
end

--HOWTO ?? Asynchronous execution of this macro when current directory is changed 
if fileExist('Gruntfile.js') or fileExist('GruntFile.js')  then
	for line in nyagos.atou(nyagos.eval('grunt --version --verbose')):gmatch('[^\n]+') do
		line:gmatch('$()')
		local pattern= 'Available tasks: '
		local pos =  line:find(pattern)
		if not(pos ==nil) then
			local tasks = line:sub(string.len(pattern) + 1)
			for i in string.gmatch(tasks, "%S+") do
				-- HOWTO ?? add this list to autocompletion of 'grunt' command
				print(i)
			end
		end
	end 
else
    print('No GruntFile NOT detected')
end
```

Currently , I have parsed correctly command line result of 'grunt --version --verbose' but I don't know how to make 'HOWTO ??' cmmented lines.

Could you help me?

**Comment by zetamatta** [comment]
I am very sorry for responding late.

 I have considered you want to know how to do `eval $(...)` on nyagos.
Now, I found you want to know how to extend the completion of nyagos.

[catalog.d/subcomplete.lua](https://github.com/zetamatta/nyagos/blob/master/catalog.d/subcomplete.lua) is a script to extend completion for git and hg's sub-command. It may be the example for you.

It calls not nyagos.eval() & nyagos.atou() but io.popen(). If `grunt` prints ascii-code only (=not prints utf8), io.popen() causes no problems.
